/* This version handles specific implemenation situations */
CREATE
	OR REPLACE FUNCTION GET_OBJECT_DEPENDENCIES ( IN SCHEMA_NAME NVARCHAR(256) DEFAULT 'SAPHANADB',
		 IN QUALIFIED_NAME NVARCHAR(256) DEFAULT '0BW:BIA:CP_PAN_6H_V3:QO',
		 IN P_SIZE NVARCHAR(1) DEFAULT ' ' ) RETURNS TABLE ( ROW_NUM INTEGER,
		 SCHEMA_NAME NVARCHAR(256) ,
		 OBJECT_NAME NVARCHAR(310) ,
		 LVL NVARCHAR(3),
		   BW_OBJECT  NVARCHAR(5000),
		   BW_OBJECT_TYPE  NVARCHAR(256),
		   BW4_PROVIDER NVARCHAR(5000),
		 DEPENDENT_OBJECT NVARCHAR(4000)
	 ) 	
		 LANGUAGE SQLSCRIPT SQL SECURITY DEFINER READS SQL DATA AS
	BEGIN BASIS_INFO = SELECT
		 "SCHEMA_NAME",
		 "OBJECT_NAME",
		 :P_SIZE AS "INCLUDE_SIZE_INFORMATION",
		 2 AS "INDENT_LENGTH"
	FROM "SYS"."OBJECTS"
	WHERE "SCHEMA_NAME" = :SCHEMA_NAME
	AND "OBJECT_NAME" = :QUALIFIED_NAME
	;
	 OD = SELECT
		 OD.BASE_SCHEMA_NAME,
		 OD.BASE_OBJECT_NAME,
		 OD.BASE_OBJECT_TYPE,
		 CASE WHEN BI.INCLUDE_SIZE_INFORMATION = 'X'
	AND T1.DISK_SIZE IS NOT NULL
	THEN ',' || CHAR(32) || TO_VARCHAR(TO_DECIMAL(T1.DISK_SIZE / 1024 / 1024 / 1024,
		 10,
		 2)) || CHAR(32) || 'GB'
	ELSE ''
	END BASE_OBJECT_SIZE_GB,
		 OD.DEPENDENT_SCHEMA_NAME,
		 OD.DEPENDENT_OBJECT_NAME,
		 OD.DEPENDENT_OBJECT_TYPE,
		 CASE WHEN BI.INCLUDE_SIZE_INFORMATION = 'X'
	AND T2.DISK_SIZE IS NOT NULL
	THEN ',' || CHAR(32) || TO_VARCHAR(TO_DECIMAL(T2.DISK_SIZE / 1024 / 1024 / 1024,
		 10,
		 2)) || CHAR(32) || 'GB'
	ELSE ''
	END DEPENDENT_OBJECT_SIZE_GB,
		 OD.DEPENDENCY_TYPE
	FROM :BASIS_INFO BI,
		 "SYS"."OBJECT_DEPENDENCIES" OD
	LEFT OUTER JOIN M_TABLE_PERSISTENCE_STATISTICS T1 ON T1.SCHEMA_NAME = OD.BASE_SCHEMA_NAME
	AND T1.TABLE_NAME = OD.BASE_OBJECT_NAME
	AND OD.BASE_OBJECT_TYPE = 'TABLE'
	LEFT OUTER JOIN M_TABLE_PERSISTENCE_STATISTICS T2 ON T2.SCHEMA_NAME = OD.BASE_SCHEMA_NAME
	AND T2.TABLE_NAME = OD.BASE_OBJECT_NAME
	AND OD.DEPENDENT_OBJECT_TYPE = 'TABLE'
	;
	 TEMP = SELECT
		 ROW_NUMBER() OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME
		ORDER BY D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14) AS ROW_NUM,
		 MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME
			ORDER BY D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 S.SCHEMA_NAME,
		 '') AS SCHEMA_NAME,
		 MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME
			ORDER BY D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 S.OBJECT_NAME,
		 '') AS OBJECT_NAME,
		 LPAD(S.LEVEL,
		 3) LVL,
		 SUBSTRING(MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1
				ORDER BY D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 D1,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2
				ORDER BY D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH ) || D2,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3
				ORDER BY D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 2) || D3,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4
				ORDER BY D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 3) || D4,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5
				ORDER BY D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 4) || D5,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6
				ORDER BY D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 5) || D6,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7
				ORDER BY D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 6) || D7,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8
				ORDER BY D9,
		 D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 7) || D8,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9
				ORDER BY D10,
		 D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 8) || D9,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10
				ORDER BY D11,
		 D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 9) || D10,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11
				ORDER BY D12,
		 D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 10) || D11,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12
				ORDER BY D13,
		 D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 11) || D12,
		 '') || MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME,
		 S.OBJECT_NAME,
		 D1,
		 D2,
		 D3,
		 D4,
		 D5,
		 D6,
		 D7,
		 D8,
		 D9,
		 D10,
		 D11,
		 D12,
		 D13
				ORDER BY D14),
		 1,
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 12) || D13,
		 '') || MAP(D14,
		 '',
		 '',
		 LPAD(CHAR(32),
		 BI.INDENT_LENGTH * 13) || D14),
		 1,
		 4000) AS DEPENDENT_OBJECT
	FROM :BASIS_INFO BI,
		 ( SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 1 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 '' D2,
		 '' D3,
		 '' D4,
		 '' D5,
		 '' D6,
		 '' D7,
		 '' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 2 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 '' D3,
		 '' D4,
		 '' D5,
		 '' D6,
		 '' D7,
		 '' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 3 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 '' D4,
		 '' D5,
		 '' D6,
		 '' D7,
		 '' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 4 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 '' D5,
		 '' D6,
		 '' D7,
		 '' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 5 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 '' D6,
		 '' D7,
		 '' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 6 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 '' D7,
		 '' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 7 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 '' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 8 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
		 '' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7,
		 :OD D8
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME
		AND D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME
		AND D8.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 9 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
		 D9.BASE_OBJECT_NAME || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE || D9.BASE_OBJECT_SIZE_GB || ')' D9,
		 '' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7,
		 :OD D8,
		 :OD D9
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME
		AND D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME
		AND D8.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME
		AND D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME
		AND D9.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 10 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
		 D9.BASE_OBJECT_NAME || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE || D9.BASE_OBJECT_SIZE_GB || ')' D9,
		 D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
		 '' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7,
		 :OD D8,
		 :OD D9,
		 :OD D10
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME
		AND D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME
		AND D8.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME
		AND D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME
		AND D9.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME
		AND D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME
		AND D10.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 11 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
		 D9.BASE_OBJECT_NAME || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE || D9.BASE_OBJECT_SIZE_GB || ')' D9,
		 D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
		 D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
		 '' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7,
		 :OD D8,
		 :OD D9,
		 :OD D10,
		 :OD D11
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME
		AND D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME
		AND D8.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME
		AND D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME
		AND D9.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME
		AND D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME
		AND D10.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME
		AND D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME
		AND D11.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 12 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
		 D9.BASE_OBJECT_NAME || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE || D9.BASE_OBJECT_SIZE_GB || ')' D9,
		 D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
		 D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
		 D12.BASE_OBJECT_NAME || CHAR(32) || '(' || D12.BASE_OBJECT_TYPE || D12.BASE_OBJECT_SIZE_GB || ')' D12,
		 '' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7,
		 :OD D8,
		 :OD D9,
		 :OD D10,
		 :OD D11,
		 :OD D12
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME
		AND D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME
		AND D8.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME
		AND D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME
		AND D9.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME
		AND D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME
		AND D10.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME
		AND D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME
		AND D11.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D12.DEPENDENT_SCHEMA_NAME = D11.BASE_SCHEMA_NAME
		AND D12.DEPENDENT_OBJECT_NAME = D11.BASE_OBJECT_NAME
		AND D12.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 13 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
		 D9.BASE_OBJECT_NAME || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE || D9.BASE_OBJECT_SIZE_GB || ')' D9,
		 D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
		 D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
		 D12.BASE_OBJECT_NAME || CHAR(32) || '(' || D12.BASE_OBJECT_TYPE || D12.BASE_OBJECT_SIZE_GB || ')' D12,
		 D13.BASE_OBJECT_NAME || CHAR(32) || '(' || D13.BASE_OBJECT_TYPE || D13.BASE_OBJECT_SIZE_GB || ')' D13,
		 '' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7,
		 :OD D8,
		 :OD D9,
		 :OD D10,
		 :OD D11,
		 :OD D12,
		 :OD D13
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME
		AND D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME
		AND D8.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME
		AND D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME
		AND D9.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME
		AND D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME
		AND D10.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME
		AND D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME
		AND D11.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D12.DEPENDENT_SCHEMA_NAME = D11.BASE_SCHEMA_NAME
		AND D12.DEPENDENT_OBJECT_NAME = D11.BASE_OBJECT_NAME
		AND D12.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D13.DEPENDENT_SCHEMA_NAME = D12.BASE_SCHEMA_NAME
		AND D13.DEPENDENT_OBJECT_NAME = D12.BASE_OBJECT_NAME
		AND D13.DEPENDENCY_TYPE IN ( 1,
		 4 )
		UNION ALL SELECT
		 D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
		 D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
		 14 LEVEL,
		 D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
		 D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
		 D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
		 D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
		 D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
		 D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
		 D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
		 D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
		 D9.BASE_OBJECT_NAME || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE || D9.BASE_OBJECT_SIZE_GB || ')' D9,
		 D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
		 D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
		 D12.BASE_OBJECT_NAME || CHAR(32) || '(' || D12.BASE_OBJECT_TYPE || D12.BASE_OBJECT_SIZE_GB || ')' D12,
		 D13.BASE_OBJECT_NAME || CHAR(32) || '(' || D13.BASE_OBJECT_TYPE || D13.BASE_OBJECT_SIZE_GB || ')' D13,
		 D14.BASE_OBJECT_NAME || CHAR(32) || '(' || D14.BASE_OBJECT_TYPE || D14.BASE_OBJECT_SIZE_GB || ')' D14
		FROM :BASIS_INFO BI,
		 :OD D1,
		 :OD D2,
		 :OD D3,
		 :OD D4,
		 :OD D5,
		 :OD D6,
		 :OD D7,
		 :OD D8,
		 :OD D9,
		 :OD D10,
		 :OD D11,
		 :OD D12,
		 :OD D13,
		 :OD D14
		WHERE D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME
		AND D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME
		AND D1.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME
		AND D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME
		AND D2.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME
		AND D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME
		AND D3.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME
		AND D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME
		AND D4.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME
		AND D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME
		AND D5.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME
		AND D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME
		AND D6.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME
		AND D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME
		AND D7.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME
		AND D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME
		AND D8.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME
		AND D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME
		AND D9.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME
		AND D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME
		AND D10.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME
		AND D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME
		AND D11.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D12.DEPENDENT_SCHEMA_NAME = D11.BASE_SCHEMA_NAME
		AND D12.DEPENDENT_OBJECT_NAME = D11.BASE_OBJECT_NAME
		AND D12.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D13.DEPENDENT_SCHEMA_NAME = D12.BASE_SCHEMA_NAME
		AND D13.DEPENDENT_OBJECT_NAME = D12.BASE_OBJECT_NAME
		AND D13.DEPENDENCY_TYPE IN ( 1,
		 4 )
		AND D14.DEPENDENT_SCHEMA_NAME = D13.BASE_SCHEMA_NAME
		AND D14.DEPENDENT_OBJECT_NAME = D13.BASE_OBJECT_NAME
		AND D14.DEPENDENCY_TYPE IN ( 1,
		 4 ) )AS S
	ORDER BY S.SCHEMA_NAME DESC,
		 S.OBJECT_NAME DESC,
		 S.D1,
		 S.D2,
		 S.D3,
		 S.D4,
		 S.D5,
		 S.D6,
		 S.D7,
		 S.D8,
		 S.D9,
		 S.D10,
		 S.D11,
		 S.D12,
		 S.D13,
		 S.D14
	;
	 RESULT = SELECT
		 "ROW_NUM",
		 "SCHEMA_NAME",
		 "OBJECT_NAME",
		"LVL",
		 "DEPENDENT_OBJECT"
	FROM :TEMP
	WHERE "DEPENDENT_OBJECT" NOT LIKE '%RSPMREQUEST%'
	AND "DEPENDENT_OBJECT" NOT LIKE '%RSDCUBE%'
	AND "DEPENDENT_OBJECT" NOT LIKE '%RSDODSO%'
	AND "DEPENDENT_OBJECT" NOT LIKE '%RSIPRORANGE%'
	AND "DEPENDENT_OBJECT" NOT LIKE '%RSMDATASTATE%'
	AND "DEPENDENT_OBJECT" NOT LIKE '%RSOADSOLOC%'
	AND "DEPENDENT_OBJECT" NOT LIKE '%0bw:pruning:rsiprorange%'
	;
	 DIST_SCHEMA_OBJ = SELECT
		 DISTINCT "SCHEMA_NAME",
		 "OBJECT_NAME"
	FROM :TEMP
	WHERE "SCHEMA_NAME" <> ''
	AND "OBJECT_NAME" <> ''
	;
	 DEPENDENT_OBJECT_1 = SELECT
		 R.ROW_NUM,
		 D.SCHEMA_NAME,
		 D.OBJECT_NAME,
		 R.LVL,
		 R.DEPENDENT_OBJECT
	FROM :RESULT AS R CROSS JOIN :DIST_SCHEMA_OBJ AS D
	ORDER BY R.ROW_NUM ASC
	;
	 DEPENDENT_OBJECT_2 = SELECT
		 ROW_NUM,
		 SCHEMA_NAME,
		 OBJECT_NAME,
		 LVL,
		 REPLACE(REPLACE(DEPENDENT_OBJECT,CHAR(40),CHAR(9)),CHAR(41),'') AS DEPENDENT_OBJECT,
		 SUBSTR_REGEXPR('([^\ ]+)' IN LTRIM(DEPENDENT_OBJECT) GROUP 1 )as BW_OBJECT,
		   CASE
			WHEN SUBSTR_REGEXPR('([^/]+)' IN LTRIM(DEPENDENT_OBJECT) GROUP 1 ) IN ('BI0','BIH','BIC')
			THEN 'INFOOBJECT'
			ELSE 'OBJECT'
		   END AS BW_OBJECT_TYPE	
	FROM :DEPENDENT_OBJECT_1 ;
	
DEPENDENT_OBJECT_3 =
SELECT
 ROW_NUM,
 SCHEMA_NAME,
 OBJECT_NAME,
 LVL,
 BW_OBJECT,
 BW_OBJECT_TYPE,
CASE BW_OBJECT_TYPE
 WHEN 'INFOOBJECT' THEN SUBSTRING(BW_OBJECT,7,22)
 WHEN 'OBJECT' THEN BW_OBJECT
ELSE 'Unknown'
END AS BW4_PROVIDER,
DEPENDENT_OBJECT
FROM :DEPENDENT_OBJECT_2
	;
DEPENDENT_OBJECT_4 =
SELECT
ROW_NUM,
SCHEMA_NAME,
OBJECT_NAME,
LVL,
BW_OBJECT,
BW_OBJECT_TYPE,

CASE
WHEN SUBSTRING(BW_OBJECT,1,6) = '/B1H/A' THEN SUBSTRING(REPLACE(BW_OBJECT,'/B1H/A','/IMO/'),1,11)
WHEN SUBSTRING(BW_OBJECT,1,6) = '/BIC/A' THEN SUBSTRING(LTRIM(BW_OBJECT,'/BIC/A'),1,LENGTH(LTRIM(BW_OBJECT,'/BIC/A'))-1)
ELSE
BW4_PROVIDER
END AS BW4_PROVIDER,
DEPENDENT_OBJECT

FROM :DEPENDENT_OBJECT_3
ORDER BY ROW_NUM
;
DEPENDENT_OBJECT_5 =
SELECT
ROW_NUM,
SCHEMA_NAME,
OBJECT_NAME,
LVL,
BW_OBJECT,
BW_OBJECT_TYPE,

CASE
WHEN BW4_PROVIDER = 'MUCAD13' THEN 'CMUCAD13'
WHEN BW4_PROVIDER = 'MATRS43' THEN 'CMATRS43'
WHEN BW4_PROVIDER = 'MFICA21' THEN  'CMFICA21'
WHEN BW4_PROVIDER NOT IN ('QM_MANUM','QM_QSNUM') AND SUBSTRING(BW4_PROVIDER,1,1) <> 'Z' AND SUBSTRING(BW4_PROVIDER,1,2) <> 'D_' AND BW_OBJECT_TYPE = 'INFOOBJECT_ADSO' THEN '0'||BW4_PROVIDER
WHEN BW4_PROVIDER IN ('/IMO/D_MMIM','/IMO/D_FIAA','/IMO/D_FICA') THEN SUBSTRING(REPLACE(BW_OBJECT,'/B1H/A','/IMO/'),1,13)
WHEN BW4_PROVIDER IN ('/IMO/D_NWA2','/IMO/D_WBS2') THEN SUBSTRING(REPLACE(BW_OBJECT,'/B1H/A','/IMO/'),1,12)
ELSE
BW4_PROVIDER
END AS BW4_PROVIDER,
DEPENDENT_OBJECT

FROM :DEPENDENT_OBJECT_4;

DEPENDENT_OBJECT_6 =
SELECT
ROW_NUM,
SCHEMA_NAME,
OBJECT_NAME,
LVL,
BW_OBJECT,

CASE
WHEN NOT A.ADSONM IS NULL THEN 'ADSO'
WHEN NOT M.IOBJNM IS NULL OR NOT O.IOBJNM IS NULL THEN 'INFOOBJECT'
ELSE 'OBJECT'
END AS BW_OBJECT_TYPE,

CASE WHEN NOT M.IOBJNM IS NULL THEN M.IOBJNM ELSE R.BW4_PROVIDER END AS BW4_PROVIDER,
DEPENDENT_OBJECT

FROM :DEPENDENT_OBJECT_5 AS R
LEFT OUTER JOIN RSOADSOT AS A ON R.BW4_PROVIDER = A.ADSONM AND A.LANGU = 'F' AND A.TTYP = 'EUSR' AND A.OBJVERS = 'A'
LEFT OUTER JOIN RSDIOBJT AS O ON R.BW4_PROVIDER = O.IOBJNM AND O.LANGU = 'F' AND O.OBJVERS = 'A'
LEFT OUTER JOIN RSDIOBJT AS OE ON R.BW4_PROVIDER = OE.IOBJNM AND OE.LANGU = 'E' AND OE.OBJVERS = 'A'
LEFT OUTER JOIN RSDIOBJT AS M ON '0'||R.BW4_PROVIDER = M.IOBJNM AND M.LANGU = 'F' AND M.OBJVERS = 'A'
;
RETURN
SELECT * FROM :DEPENDENT_OBJECT_6;
	
END
;
