/*

[DESCRIPTION]

- This Script is a mere copy/paste from  Script Delivered by SAP in SAP OSS 1969700
- Executable in SAP HANA Data Explorer for example in a SAP DataSphere Instance 
- Maintainability up to release HANA 2.0 SPS8
*/

WITH 

BASIS_INFO AS
(    SELECT                /* Modification section 0BW:BIA:CP_PAN_6H_V3 /BIC/VCP_PAN_6H_V38*/
    "SCHEMA_NAME",
    "OBJECT_NAME",
    'X' AS "INCLUDE_SIZE_INFORMATION",
    2 AS "INDENT_LENGTH"
    FROM "SYS"."OBJECTS"
    WHERE SCHEMA_NAME = 'SPACE001' AND OBJECT_NAME = 'VG_ISU_MASTERDATA_FACT' /*AM_REVASSUR_02 VG_ISU_MASTERDATA_FACT BW_DSP_LINEAGE_AUDIT*/
)
,
OD AS
( SELECT 
    OD.BASE_SCHEMA_NAME,
    OD.BASE_OBJECT_NAME,
    OD.BASE_OBJECT_TYPE,
    CASE WHEN BI.INCLUDE_SIZE_INFORMATION = 'X' AND T1.DISK_SIZE IS NOT NULL THEN ',' || CHAR(32) || TO_VARCHAR(TO_DECIMAL(T1.DISK_SIZE / 1024 / 1024 / 1024, 10, 2)) || CHAR(32) || 'GB'  ELSE '' END BASE_OBJECT_SIZE_GB,
    OD.DEPENDENT_SCHEMA_NAME,
    OD.DEPENDENT_OBJECT_NAME,
    OD.DEPENDENT_OBJECT_TYPE,
    CASE WHEN BI.INCLUDE_SIZE_INFORMATION = 'X' AND T2.DISK_SIZE IS NOT NULL THEN ',' || CHAR(32) || TO_VARCHAR(TO_DECIMAL(T2.DISK_SIZE / 1024 / 1024 / 1024, 10, 2)) || CHAR(32) || 'GB' ELSE '' END DEPENDENT_OBJECT_SIZE_GB,
    OD.DEPENDENCY_TYPE
  FROM
    BASIS_INFO BI,
    OBJECT_DEPENDENCIES OD LEFT OUTER JOIN
    M_TABLE_PERSISTENCE_STATISTICS T1 ON
      T1.SCHEMA_NAME = OD.BASE_SCHEMA_NAME AND
      T1.TABLE_NAME = OD.BASE_OBJECT_NAME AND
      OD.BASE_OBJECT_TYPE = 'TABLE' LEFT OUTER JOIN
    M_TABLE_PERSISTENCE_STATISTICS T2 ON
      T2.SCHEMA_NAME = OD.BASE_SCHEMA_NAME AND
      T2.TABLE_NAME = OD.BASE_OBJECT_NAME AND
      OD.DEPENDENT_OBJECT_TYPE = 'TABLE'
)
,
TEMP AS
(
SELECT
ROW_NUMBER() OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME ORDER BY D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14) AS row_num,
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME ORDER BY D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14), 1, S.SCHEMA_NAME, '') SCHEMA_NAME,
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME ORDER BY D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14), 1, S.OBJECT_NAME, '') OBJECT_NAME,
  LPAD(S.LEVEL, 3) LVL,
  SUBSTR(MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1 ORDER BY D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14), 1, D1, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2 ORDER BY D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH     ) ||  D2, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3 ORDER BY D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  2) ||  D3, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4 ORDER BY D5, D6, D7, D8, D9, D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  3) ||  D4, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5 ORDER BY D6, D7, D8, D9, D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  4) ||  D5, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6 ORDER BY D7, D8, D9, D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  5) ||  D6, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6, D7 ORDER BY D8, D9, D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  6) ||  D7, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6, D7, D8 ORDER BY D9, D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  7) ||  D8, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6, D7, D8, D9 ORDER BY D10, D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  8) ||  D9, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10 ORDER BY D11, D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH *  9) || D10, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11 ORDER BY D12, D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH * 10) || D11, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12 ORDER BY D13, D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH * 11) || D12, '') ||
  MAP(ROW_NUMBER () OVER (PARTITION BY S.SCHEMA_NAME, S.OBJECT_NAME, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13 ORDER BY D14), 1, LPAD(CHAR(32), BI.INDENT_LENGTH * 12) || D13, '') ||
  MAP(D14, '', '', LPAD(CHAR(32), BI.INDENT_LENGTH * 13) || D14), 1, 4000) DEPENDENT_OBJECT
FROM
  BASIS_INFO BI,
( SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    1 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    '' D2,
    '' D3,
    '' D4,
    '' D5,
    '' D6,
    '' D7,
    '' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    2 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    '' D3,
    '' D4,
    '' D5,
    '' D6,
    '' D7,
    '' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    3 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
    '' D4,
    '' D5,
    '' D6,
    '' D7,
    '' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    4 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
    D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
    '' D5,
    '' D6,
    '' D7,
    '' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    5 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
    D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
    D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
    '' D6,
    '' D7,
    '' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    6 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
    D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
    D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
    D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
    '' D7,
    '' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    7 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
    D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
    D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
    D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
    D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
    '' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    8 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
    D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
    D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
    D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
    D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
    D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
    '' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7,
    OD D8
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME AND
    D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME AND
    D8.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    9 LEVEL,
    D1.BASE_OBJECT_NAME || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE || D1.BASE_OBJECT_SIZE_GB || ')' D1,
    D2.BASE_OBJECT_NAME || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE || D2.BASE_OBJECT_SIZE_GB || ')' D2,
    D3.BASE_OBJECT_NAME || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE || D3.BASE_OBJECT_SIZE_GB || ')' D3,
    D4.BASE_OBJECT_NAME || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE || D4.BASE_OBJECT_SIZE_GB || ')' D4,
    D5.BASE_OBJECT_NAME || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE || D5.BASE_OBJECT_SIZE_GB || ')' D5,
    D6.BASE_OBJECT_NAME || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE || D6.BASE_OBJECT_SIZE_GB || ')' D6,
    D7.BASE_OBJECT_NAME || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE || D7.BASE_OBJECT_SIZE_GB || ')' D7,
    D8.BASE_OBJECT_NAME || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE || D8.BASE_OBJECT_SIZE_GB || ')' D8,
    D9.BASE_OBJECT_NAME || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE || D9.BASE_OBJECT_SIZE_GB || ')' D9,
    '' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7,
    OD D8,
    OD D9
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME AND
    D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME AND
    D8.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME AND
    D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME AND
    D9.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    10 LEVEL,
    D1.BASE_OBJECT_NAME  || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE  || D1.BASE_OBJECT_SIZE_GB  || ')' D1,
    D2.BASE_OBJECT_NAME  || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE  || D2.BASE_OBJECT_SIZE_GB  || ')' D2,
    D3.BASE_OBJECT_NAME  || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE  || D3.BASE_OBJECT_SIZE_GB  || ')' D3,
    D4.BASE_OBJECT_NAME  || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE  || D4.BASE_OBJECT_SIZE_GB  || ')' D4,
    D5.BASE_OBJECT_NAME  || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE  || D5.BASE_OBJECT_SIZE_GB  || ')' D5,
    D6.BASE_OBJECT_NAME  || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE  || D6.BASE_OBJECT_SIZE_GB  || ')' D6,
    D7.BASE_OBJECT_NAME  || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE  || D7.BASE_OBJECT_SIZE_GB  || ')' D7,
    D8.BASE_OBJECT_NAME  || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE  || D8.BASE_OBJECT_SIZE_GB  || ')' D8,
    D9.BASE_OBJECT_NAME  || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE  || D9.BASE_OBJECT_SIZE_GB  || ')' D9,
    D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
    '' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7,
    OD D8,
    OD D9,
    OD D10
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME AND
    D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME AND
    D8.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME AND
    D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME AND
    D9.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME AND
    D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME AND
    D10.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    11 LEVEL,
    D1.BASE_OBJECT_NAME  || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE  || D1.BASE_OBJECT_SIZE_GB  || ')' D1,
    D2.BASE_OBJECT_NAME  || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE  || D2.BASE_OBJECT_SIZE_GB  || ')' D2,
    D3.BASE_OBJECT_NAME  || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE  || D3.BASE_OBJECT_SIZE_GB  || ')' D3,
    D4.BASE_OBJECT_NAME  || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE  || D4.BASE_OBJECT_SIZE_GB  || ')' D4,
    D5.BASE_OBJECT_NAME  || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE  || D5.BASE_OBJECT_SIZE_GB  || ')' D5,
    D6.BASE_OBJECT_NAME  || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE  || D6.BASE_OBJECT_SIZE_GB  || ')' D6,
    D7.BASE_OBJECT_NAME  || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE  || D7.BASE_OBJECT_SIZE_GB  || ')' D7,
    D8.BASE_OBJECT_NAME  || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE  || D8.BASE_OBJECT_SIZE_GB  || ')' D8,
    D9.BASE_OBJECT_NAME  || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE  || D9.BASE_OBJECT_SIZE_GB  || ')' D9,
    D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
    D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
    '' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7,
    OD D8,
    OD D9,
    OD D10,
    OD D11
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME AND
    D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME AND
    D8.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME AND
    D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME AND
    D9.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME AND
    D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME AND
    D10.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME AND
    D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME AND
    D11.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    12 LEVEL,
    D1.BASE_OBJECT_NAME  || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE  || D1.BASE_OBJECT_SIZE_GB  || ')' D1,
    D2.BASE_OBJECT_NAME  || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE  || D2.BASE_OBJECT_SIZE_GB  || ')' D2,
    D3.BASE_OBJECT_NAME  || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE  || D3.BASE_OBJECT_SIZE_GB  || ')' D3,
    D4.BASE_OBJECT_NAME  || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE  || D4.BASE_OBJECT_SIZE_GB  || ')' D4,
    D5.BASE_OBJECT_NAME  || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE  || D5.BASE_OBJECT_SIZE_GB  || ')' D5,
    D6.BASE_OBJECT_NAME  || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE  || D6.BASE_OBJECT_SIZE_GB  || ')' D6,
    D7.BASE_OBJECT_NAME  || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE  || D7.BASE_OBJECT_SIZE_GB  || ')' D7,
    D8.BASE_OBJECT_NAME  || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE  || D8.BASE_OBJECT_SIZE_GB  || ')' D8,
    D9.BASE_OBJECT_NAME  || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE  || D9.BASE_OBJECT_SIZE_GB  || ')' D9,
    D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
    D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
    D12.BASE_OBJECT_NAME || CHAR(32) || '(' || D12.BASE_OBJECT_TYPE || D12.BASE_OBJECT_SIZE_GB || ')' D12,
    '' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7,
    OD D8,
    OD D9,
    OD D10,
    OD D11,
    OD D12
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME AND
    D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME AND
    D8.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME AND
    D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME AND
    D9.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME AND
    D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME AND
    D10.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME AND
    D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME AND
    D11.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D12.DEPENDENT_SCHEMA_NAME = D11.BASE_SCHEMA_NAME AND
    D12.DEPENDENT_OBJECT_NAME = D11.BASE_OBJECT_NAME AND
    D12.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    13 LEVEL,
    D1.BASE_OBJECT_NAME  || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE  || D1.BASE_OBJECT_SIZE_GB  || ')' D1,
    D2.BASE_OBJECT_NAME  || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE  || D2.BASE_OBJECT_SIZE_GB  || ')' D2,
    D3.BASE_OBJECT_NAME  || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE  || D3.BASE_OBJECT_SIZE_GB  || ')' D3,
    D4.BASE_OBJECT_NAME  || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE  || D4.BASE_OBJECT_SIZE_GB  || ')' D4,
    D5.BASE_OBJECT_NAME  || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE  || D5.BASE_OBJECT_SIZE_GB  || ')' D5,
    D6.BASE_OBJECT_NAME  || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE  || D6.BASE_OBJECT_SIZE_GB  || ')' D6,
    D7.BASE_OBJECT_NAME  || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE  || D7.BASE_OBJECT_SIZE_GB  || ')' D7,
    D8.BASE_OBJECT_NAME  || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE  || D8.BASE_OBJECT_SIZE_GB  || ')' D8,
    D9.BASE_OBJECT_NAME  || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE  || D9.BASE_OBJECT_SIZE_GB  || ')' D9,
    D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
    D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
    D12.BASE_OBJECT_NAME || CHAR(32) || '(' || D12.BASE_OBJECT_TYPE || D12.BASE_OBJECT_SIZE_GB || ')' D12,
    D13.BASE_OBJECT_NAME || CHAR(32) || '(' || D13.BASE_OBJECT_TYPE || D13.BASE_OBJECT_SIZE_GB || ')' D13,
    '' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7,
    OD D8,
    OD D9,
    OD D10,
    OD D11,
    OD D12,
    OD D13
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME AND
    D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME AND
    D8.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME AND
    D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME AND
    D9.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME AND
    D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME AND
    D10.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME AND
    D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME AND
    D11.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D12.DEPENDENT_SCHEMA_NAME = D11.BASE_SCHEMA_NAME AND
    D12.DEPENDENT_OBJECT_NAME = D11.BASE_OBJECT_NAME AND
    D12.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D13.DEPENDENT_SCHEMA_NAME = D12.BASE_SCHEMA_NAME AND
    D13.DEPENDENT_OBJECT_NAME = D12.BASE_OBJECT_NAME AND
    D13.DEPENDENCY_TYPE IN ( 1, 4 )
  UNION ALL
  SELECT
    D1.DEPENDENT_SCHEMA_NAME SCHEMA_NAME,
    D1.DEPENDENT_OBJECT_NAME || CHAR(32) || '(' || D1.DEPENDENT_OBJECT_TYPE || D1.DEPENDENT_OBJECT_SIZE_GB || ')' OBJECT_NAME,
    14 LEVEL,
    D1.BASE_OBJECT_NAME  || CHAR(32) || '(' || D1.BASE_OBJECT_TYPE  || D1.BASE_OBJECT_SIZE_GB  || ')' D1,
    D2.BASE_OBJECT_NAME  || CHAR(32) || '(' || D2.BASE_OBJECT_TYPE  || D2.BASE_OBJECT_SIZE_GB  || ')' D2,
    D3.BASE_OBJECT_NAME  || CHAR(32) || '(' || D3.BASE_OBJECT_TYPE  || D3.BASE_OBJECT_SIZE_GB  || ')' D3,
    D4.BASE_OBJECT_NAME  || CHAR(32) || '(' || D4.BASE_OBJECT_TYPE  || D4.BASE_OBJECT_SIZE_GB  || ')' D4,
    D5.BASE_OBJECT_NAME  || CHAR(32) || '(' || D5.BASE_OBJECT_TYPE  || D5.BASE_OBJECT_SIZE_GB  || ')' D5,
    D6.BASE_OBJECT_NAME  || CHAR(32) || '(' || D6.BASE_OBJECT_TYPE  || D6.BASE_OBJECT_SIZE_GB  || ')' D6,
    D7.BASE_OBJECT_NAME  || CHAR(32) || '(' || D7.BASE_OBJECT_TYPE  || D7.BASE_OBJECT_SIZE_GB  || ')' D7,
    D8.BASE_OBJECT_NAME  || CHAR(32) || '(' || D8.BASE_OBJECT_TYPE  || D8.BASE_OBJECT_SIZE_GB  || ')' D8,
    D9.BASE_OBJECT_NAME  || CHAR(32) || '(' || D9.BASE_OBJECT_TYPE  || D9.BASE_OBJECT_SIZE_GB  || ')' D9,
    D10.BASE_OBJECT_NAME || CHAR(32) || '(' || D10.BASE_OBJECT_TYPE || D10.BASE_OBJECT_SIZE_GB || ')' D10,
    D11.BASE_OBJECT_NAME || CHAR(32) || '(' || D11.BASE_OBJECT_TYPE || D11.BASE_OBJECT_SIZE_GB || ')' D11,
    D12.BASE_OBJECT_NAME || CHAR(32) || '(' || D12.BASE_OBJECT_TYPE || D12.BASE_OBJECT_SIZE_GB || ')' D12,
    D13.BASE_OBJECT_NAME || CHAR(32) || '(' || D13.BASE_OBJECT_TYPE || D13.BASE_OBJECT_SIZE_GB || ')' D13,
    D14.BASE_OBJECT_NAME || CHAR(32) || '(' || D14.BASE_OBJECT_TYPE || D14.BASE_OBJECT_SIZE_GB || ')' D14
  FROM
    BASIS_INFO BI,
    OD D1,
    OD D2,
    OD D3,
    OD D4,
    OD D5,
    OD D6,
    OD D7,
    OD D8,
    OD D9,
    OD D10,
    OD D11,
    OD D12,
    OD D13,
    OD D14
  WHERE
    D1.DEPENDENT_SCHEMA_NAME LIKE BI.SCHEMA_NAME AND
    D1.DEPENDENT_OBJECT_NAME LIKE BI.OBJECT_NAME AND
    D1.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D2.DEPENDENT_SCHEMA_NAME = D1.BASE_SCHEMA_NAME AND
    D2.DEPENDENT_OBJECT_NAME = D1.BASE_OBJECT_NAME AND
    D2.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D3.DEPENDENT_SCHEMA_NAME = D2.BASE_SCHEMA_NAME AND
    D3.DEPENDENT_OBJECT_NAME = D2.BASE_OBJECT_NAME AND
    D3.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D4.DEPENDENT_SCHEMA_NAME = D3.BASE_SCHEMA_NAME AND
    D4.DEPENDENT_OBJECT_NAME = D3.BASE_OBJECT_NAME AND
    D4.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D5.DEPENDENT_SCHEMA_NAME = D4.BASE_SCHEMA_NAME AND
    D5.DEPENDENT_OBJECT_NAME = D4.BASE_OBJECT_NAME AND
    D5.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D6.DEPENDENT_SCHEMA_NAME = D5.BASE_SCHEMA_NAME AND
    D6.DEPENDENT_OBJECT_NAME = D5.BASE_OBJECT_NAME AND
    D6.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D7.DEPENDENT_SCHEMA_NAME = D6.BASE_SCHEMA_NAME AND
    D7.DEPENDENT_OBJECT_NAME = D6.BASE_OBJECT_NAME AND
    D7.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D8.DEPENDENT_SCHEMA_NAME = D7.BASE_SCHEMA_NAME AND
    D8.DEPENDENT_OBJECT_NAME = D7.BASE_OBJECT_NAME AND
    D8.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D9.DEPENDENT_SCHEMA_NAME = D8.BASE_SCHEMA_NAME AND
    D9.DEPENDENT_OBJECT_NAME = D8.BASE_OBJECT_NAME AND
    D9.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D10.DEPENDENT_SCHEMA_NAME = D9.BASE_SCHEMA_NAME AND
    D10.DEPENDENT_OBJECT_NAME = D9.BASE_OBJECT_NAME AND
    D10.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D11.DEPENDENT_SCHEMA_NAME = D10.BASE_SCHEMA_NAME AND
    D11.DEPENDENT_OBJECT_NAME = D10.BASE_OBJECT_NAME AND
    D11.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D12.DEPENDENT_SCHEMA_NAME = D11.BASE_SCHEMA_NAME AND
    D12.DEPENDENT_OBJECT_NAME = D11.BASE_OBJECT_NAME AND
    D12.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D13.DEPENDENT_SCHEMA_NAME = D12.BASE_SCHEMA_NAME AND
    D13.DEPENDENT_OBJECT_NAME = D12.BASE_OBJECT_NAME AND
    D13.DEPENDENCY_TYPE IN ( 1, 4 ) AND
    D14.DEPENDENT_SCHEMA_NAME = D13.BASE_SCHEMA_NAME AND
    D14.DEPENDENT_OBJECT_NAME = D13.BASE_OBJECT_NAME AND
    D14.DEPENDENCY_TYPE IN ( 1, 4 )
) S
ORDER BY
  S.SCHEMA_NAME,
  S.OBJECT_NAME,
  S.D1,
  S.D2,
  S.D3,
  S.D4,
  S.D5,
  S.D6,
  S.D7,
  S.D8,
  S.D9,
  S.D10,
  S.D11,
  S.D12,
  S.D13,
  S.D14
)
/*
SELECT * FROM OD WHERE BASE_SCHEMA_NAME = 'SYS' AND BASE_OBJECT_NAME = 'VG_ISU_INSTALL_VF_02';
SELECT SCHEMA_NAME, OBJECT_NAME, LVL, DEPENDENT_OBJECT FROM TEMP;
*/
SELECT ROW_NUM, SCHEMA_NAME, OBJECT_NAME, LVL, DEPENDENT_OBJECT FROM TEMP;
