/*
SAP ERP HCM - OM Organizational Structure Often Obscure to summarize and validate despite SE38 RHCHECK0
This SQL will help browse the hierarchy tree
Ranking has to be adjusted based on draft sql :
SELECT DISTINCT
"RELATION"."OTYPE" AS "OBJECTTYPE", 
"T"."OTEXT",
CASE "RELATION"."RSIGN" WHEN 'A' THEN 'Bottom-Up' WHEN 'B' THEN 'Top-Down' END AS "RELATIONSHIPDIRECTION", 
"RELATION"."SUBTY",
"T4"."SUTXT",
"RELATION"."SCLAS" AS "RELATEDOBJECTTYPE",
"T3"."OTEXT" AS "RELATEDOBJECTTYPEDESC",
COUNT("RELATION"."OBJID"),
COUNT("RELATION"."SOBID")
FROM "HRP1001" AS "RELATION" 
INNER JOIN "T777O" AS "T" 
ON "T"."OTYPE" = "RELATION"."OTYPE" AND "T"."MANDT" = "RELATION"."MANDT"  
AND "T"."LANGU" = 'E'
INNER JOIN "T777V" AS T2
ON "T2"."RELAT" = "RELATION"."RELAT"  AND "T2"."MANDT" = "RELATION"."MANDT"  
AND "T2"."LANGU" = 'E'
INNER JOIN "T777O" AS "T3" 
ON "T3"."OTYPE" = "RELATION"."SCLAS" AND "T3"."MANDT" = "RELATION"."MANDT"  
AND "T3"."LANGU" = 'E'
INNER JOIN "T777U" AS "T4" 
ON "T4"."SUBTY" = "RELATION"."SUBTY" AND "T4"."INFTY" = "RELATION"."INFTY" AND "T4"."MANDT" = "RELATION"."MANDT"  
AND "T4"."LANGU" = 'E'
WHERE "RELATION"."ENDDA" = N'99991231' AND "RELATION"."MANDT" = '100' 
GROUP BY
"RELATION"."OTYPE",
"T"."OTEXT",
"RELATION"."RSIGN",
"RELATION"."SUBTY",
"T4"."SUTXT",
"RELATION"."SCLAS",
"T3"."OTEXT"
ORDER BY 1, 6, 4

*/
SELECT DISTINCT
CASE  
WHEN "RELATION"."OTYPE" = 'CP' AND "RELATION"."SCLAS" = 'P' AND "RELATION"."RSIGN" = 'B' THEN 1
WHEN "RELATION"."OTYPE" = 'P' AND "RELATION"."SCLAS" = 'CP' AND "RELATION"."RSIGN" = 'A' THEN 2
WHEN "RELATION"."OTYPE" = 'P' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."RSIGN" = 'B'  THEN 3
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'P' AND "RELATION"."RSIGN" = 'A'  THEN 4
WHEN "RELATION"."OTYPE" = 'O' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."RSIGN" = 'B'  THEN 5
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'O' AND "RELATION"."RSIGN" = 'A' THEN 6
WHEN "RELATION"."OTYPE" = 'O' AND "RELATION"."SCLAS" = 'O' AND "RELATION"."RSIGN" = 'B' THEN 7
WHEN "RELATION"."OTYPE" = 'O' AND "RELATION"."SCLAS" = 'O' AND "RELATION"."RSIGN" = 'A' THEN 8
WHEN "RELATION"."OTYPE" = 'O' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."SUBTY" = 'B012' THEN 9
WHEN "RELATION"."OTYPE" = 'O' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."SUBTY" = 'A012' THEN 10
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."RSIGN" = 'B' THEN 11
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."RSIGN" = 'A' THEN 12
WHEN "RELATION"."OTYPE" = 'O' AND "RELATION"."SCLAS" = 'RY' AND "RELATION"."RSIGN" = 'B' THEN 13
WHEN "RELATION"."OTYPE" = 'RY' AND "RELATION"."SCLAS" = 'O' AND "RELATION"."RSIGN" = 'A' THEN 14
WHEN "RELATION"."OTYPE" = 'O' AND "RELATION"."SCLAS" = 'K' AND "RELATION"."RSIGN" = 'B' THEN 15
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'K' AND "RELATION"."RSIGN" = 'A' THEN 16
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'US' AND "RELATION"."RSIGN" = 'A' THEN 17
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'C' AND "RELATION"."RSIGN" = 'B' THEN 18
WHEN "RELATION"."OTYPE" = 'C' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."RSIGN" = 'A' THEN 19
WHEN "RELATION"."OTYPE" = 'CP' AND "RELATION"."SCLAS" = 'S' AND "RELATION"."RSIGN" = 'B' THEN 20
WHEN "RELATION"."OTYPE" = 'S' AND "RELATION"."SCLAS" = 'CP' AND "RELATION"."RSIGN" = 'A' THEN 21
ELSE 99
END AS RANKING
,"RELATION"."OTYPE" AS "OBJECTTYPE", 
"T"."OTEXT",
CASE "RELATION"."RSIGN" WHEN 'A' THEN 'Bottom-Up' WHEN 'B' THEN 'Top-Down' END AS "RELATIONSHIPDIRECTION", 
"RELATION"."SUBTY",
"T4"."SUTXT",
"RELATION"."SCLAS" AS "RELATEDOBJECTTYPE",
"T3"."OTEXT" AS "RELATEDOBJECTTYPEDESC",
COUNT("RELATION"."OBJID"),
COUNT("RELATION"."SOBID")
FROM "HRP1001" AS "RELATION" 
INNER JOIN "T777O" AS "T" 
ON "T"."OTYPE" = "RELATION"."OTYPE" AND "T"."MANDT" = "RELATION"."MANDT"  
AND "T"."LANGU" = 'E'
INNER JOIN "T777V" AS T2
ON "T2"."RELAT" = "RELATION"."RELAT"  AND "T2"."MANDT" = "RELATION"."MANDT"  
AND "T2"."LANGU" = 'E'
INNER JOIN "T777O" AS "T3" 
ON "T3"."OTYPE" = "RELATION"."SCLAS" AND "T3"."MANDT" = "RELATION"."MANDT"  
AND "T3"."LANGU" = 'E'
INNER JOIN "T777U" AS "T4" 
ON "T4"."SUBTY" = "RELATION"."SUBTY" AND "T4"."INFTY" = "RELATION"."INFTY" AND "T4"."MANDT" = "RELATION"."MANDT"  
AND "T4"."LANGU" = 'E'
WHERE "RELATION"."ENDDA" = N'99991231' AND "RELATION"."MANDT" = '100' 
GROUP BY
"RELATION"."OTYPE",
"T"."OTEXT",
"RELATION"."RSIGN",
"RELATION"."SUBTY",
"T4"."SUTXT",
"RELATION"."SCLAS",
"T3"."OTEXT"
ORDER BY "RANKING" 
