WITH CTE_RV_P_STEPCATEGORY AS
(
SELECT
  "RSTCTEXTRACT"."STEP_CATEGORY" AS "STEPCATEGORY",
  "RSTCTEXTRACT"."EXTRACTION"
FROM "RSTCTEXTRACT" AS "RSTCTEXTRACT"
)
,
CTE_RV_P_OLAPSTAT AS
(
SELECT
  "RSDDSTAT_OLAP"."SESSIONUID" AS "SESSIONUID",
  "RSDDSTAT_OLAP"."STEPUID" AS "STEPUID",
  "RSDDSTAT_OLAP"."HANDLEID" AS "HANDLEID",
  "RSDDSTAT_OLAP"."HANDLETP" AS "HANDLETYPE",
  "RSDDSTAT_OLAP"."EVENTID" AS "EVENTID",
  "RSDDSTAT_OLAP"."UNAME" AS "USERNAME",
  "RSDDSTAT_OLAP"."STEPTP" AS "STEPTYPE",
  "RSDDSTAT_OLAP"."STEPCNT" AS "STEPCOUNT",
  "RSDDSTAT_OLAP"."UTIME" AS "TIME",
  "RSDDSTAT_OLAP"."CALDAY" AS "CALDAY",
  "RSDDSTAT_OLAP"."RUNTIME" AS "RUNTIME",
  "RSDDSTAT_OLAP"."INFOPROV" AS "INFOPROV",
  "RSDDSTAT_OLAP"."OBJNAME" AS "OBJNAME",
  "RSDDSTAT_OLAP"."OBJPROP" AS "OBJPROP",
  "RSDDSTAT_OLAP"."STATLEVEL" AS "STATLEVEL",
  "RSDDSTAT_OLAP"."EVTIME" AS "EVENTTIME",
  "RSDDSTAT_OLAP"."EVCOUNT" AS "EVENTCOUNT",
  "RSDDSTAT_OLAP"."EVENTIDCNT" AS "EVENTIDCOUNT",
  "RSDDSTAT_OLAP"."STARTTIME" AS "STARTTIME"
FROM "RSDDSTAT_OLAP" AS "RSDDSTAT_OLAP"
)
,
CTE_RVPOSSTEPAE AS
(
SELECT
  DISTINCT "RVPOLAPSTAT"."STEPUID"
FROM "CTE_RV_P_OLAPSTAT" AS "RVPOLAPSTAT"
WHERE (
  "RVPOLAPSTAT"."HANDLETYPE" = N'APPL' AND
  "RVPOLAPSTAT"."EVENTID" = N'000015001'
)
)
,
CTE_RVPOSSTEPHT AS
(
SELECT
  DISTINCT "S1"."STEPUID"
FROM "CTE_RV_P_OLAPSTAT" AS "S1" INNER JOIN "CTE_RV_P_STEPCATEGORY" AS "S2" ON (
  "S2"."STEPCATEGORY" = "S1"."HANDLETYPE" AND
  "S2"."EXTRACTION" = N'X'
)
WHERE (
  "S1"."HANDLETYPE" = N'MDX' OR "S1"."HANDLETYPE" = N'EXTN' OR "S1"."HANDLETYPE" = N'DIAL' OR (
    "S1"."HANDLETYPE" = N'OLAP' AND
    "S1"."EVENTID" = N'000003010'
  ) OR (
    "S1"."HANDLETYPE" = N'OLAP' AND
    "S1"."EVENTID" = N'000003100'
  )
)
)
,CTE_RVPOSSTEPHTAI AS
(
SELECT
  DISTINCT "S1"."STEPUID"
FROM "CTE_RV_P_OLAPSTAT" "S1" INNER JOIN "CTE_RV_P_STEPCATEGORY" "S2" ON (
  "S2"."STEPCATEGORY" = N'APPL' AND
  "S2"."EXTRACTION" = N'X'
)
WHERE (
  "S1"."HANDLETYPE" = N'APPL' OR "S1"."HANDLETYPE" = N'ITEM'
)
)
,
CTE_RVPOSSTEPHTO AS
(
SELECT
  DISTINCT "S1"."STEPUID"
FROM "CTE_RV_P_OLAPSTAT" "S1" INNER JOIN "CTE_RV_P_STEPCATEGORY" "S2" ON (
  "S2"."STEPCATEGORY" = N'OTHE' AND
  "S2"."EXTRACTION" = N'X'
)
WHERE ( NOT ( "S1"."HANDLETYPE" = N'MDX' ) AND NOT ( "S1"."HANDLETYPE" = N'OLAP' ) AND
  NOT ( "S1"."HANDLETYPE" = N'EXTN' ) AND NOT ( "S1"."HANDLETYPE" = N'DIAL' ) AND NOT (
    "S1"."HANDLETYPE" = N'APPL' ) AND NOT ( "S1"."HANDLETYPE" = N'ITEM' ))
)
,
CTE_RV_P_STEPUID AS
(
SELECT
  "RVPOSSTEPAE"."STEPUID"
FROM "CTE_RVPOSSTEPAE" AS "RVPOSSTEPAE"
UNION SELECT
  "RVPOSSTEPHT"."STEPUID"
FROM "CTE_RVPOSSTEPHT" AS "RVPOSSTEPHT"
UNION SELECT
  "RVPOSSTEPHTAI"."STEPUID"
FROM "CTE_RVPOSSTEPHTAI" AS "RVPOSSTEPHTAI"
UNION SELECT
  "RVPOSSTEPHTO"."STEPUID"
FROM "CTE_RVPOSSTEPHTO" AS "RVPOSSTEPHTO"
)
,
CTE_RVPOLAPSTATF AS (
SELECT
  "S1"."SESSIONUID" AS "SESSIONUID",
  "S1"."STEPUID" AS "STEPUID",
  "S1"."HANDLEID" AS "HANDLEID",
  "S1"."HANDLETYPE" AS "HANDLETYPE",
  "S1"."EVENTID" AS "EVENTID",
  "S1"."USERNAME",
  "S1"."STEPTYPE",
  "S1"."STEPCOUNT",
  "S1"."TIME",
  "S1"."CALDAY",
  "S1"."RUNTIME",
  "S1"."INFOPROV",
  "S1"."OBJNAME",
  "S1"."OBJPROP",
  "S1"."STATLEVEL",
  "S1"."EVENTTIME",
  "S1"."EVENTCOUNT",
  "S1"."EVENTIDCOUNT",
  "S1"."STARTTIME"
FROM "CTE_RV_P_OLAPSTAT" AS "S1" INNER JOIN "CTE_RV_P_STEPUID" AS "S2" ON
  "S2"."STEPUID" = "S1"."STEPUID"
)
,
CTE_RVPOLAPSTATM AS
(
SELECT
  "RVPOLAPSTATF"."SESSIONUID",
  "RVPOLAPSTATF"."STEPUID",
  "RVPOLAPSTATF"."HANDLEID",
  "RVPOLAPSTATF"."HANDLETYPE",
  "RVPOLAPSTATF"."EVENTID",
  "RVPOLAPSTATF"."USERNAME",
  "RVPOLAPSTATF"."STEPTYPE",
  "RVPOLAPSTATF"."STEPCOUNT",
  "RVPOLAPSTATF"."TIME",
  "RVPOLAPSTATF"."CALDAY",
  "RVPOLAPSTATF"."RUNTIME",
  "RVPOLAPSTATF"."INFOPROV",
  "RVPOLAPSTATF"."OBJNAME",
  "RVPOLAPSTATF"."OBJPROP",
  "RVPOLAPSTATF"."STATLEVEL",
  "RVPOLAPSTATF"."EVENTTIME",
  "RVPOLAPSTATF"."EVENTCOUNT",
  "RVPOLAPSTATF"."EVENTIDCOUNT",
  "RVPOLAPSTATF"."STARTTIME",
  (
    CASE WHEN "RVPOLAPSTATF"."EVENTID" = N'000000001' THEN 0 WHEN (
      "RVPOLAPSTATF"."HANDLETYPE" = N'W3_T' OR "RVPOLAPSTATF"."HANDLETYPE" = N'W3_I' OR "RVPOLAPSTATF"."HANDLETYPE" = N'APPL' OR "RVPOLAPSTATF"."HANDLETYPE" = N'ITEM' OR "RVPOLAPSTATF"."HANDLETYPE" = N'DP' OR "RVPOLAPSTATF"."HANDLETYPE" = N'BRFC'
    ) THEN "RVPOLAPSTATF"."EVENTTIME" WHEN (
      "RVPOLAPSTATF"."HANDLETYPE" = N'DIAL' AND
      NOT (
        "RVPOLAPSTATF"."EVENTID" = N'000015013'
      )
    ) THEN "RVPOLAPSTATF"."EVENTTIME" WHEN (
      "RVPOLAPSTATF"."HANDLETYPE" = N'OLAP' AND
      (
        "RVPOLAPSTATF"."EVENTID" = N'000019901' OR "RVPOLAPSTATF"."EVENTID" = N'000019902' OR "RVPOLAPSTATF"."EVENTID" = N'000019950' OR "RVPOLAPSTATF"."EVENTID" = N'000019951' OR "RVPOLAPSTATF"."EVENTID" = N'000019952'
      )
    ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
      0 AS DECIMAL(000021,000000)
    )
    END
  ) AS "TIMEFRONTEND",
  (
    CASE "RVPOLAPSTATF"."HANDLETYPE" WHEN N'BTCH' THEN (
      CASE WHEN NOT (
        "RVPOLAPSTATF"."EVENTID" = N'000009000'
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'MDX' THEN (
      CASE WHEN NOT (
        "RVPOLAPSTATF"."EVENTID" = N'000009000'
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'EXTN' THEN (
      CASE WHEN "RVPOLAPSTATF"."EVENTID" = N'000004500' THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'OLAP' THEN (
      CASE WHEN (
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000019901'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000019902'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000019950'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000019951'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000019952'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000009000'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000009010'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000009011'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000000001'
        )
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'F4' THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
      0 AS DECIMAL(000021,000000)
    )
    END
  ) AS "TIMEOLAP",
  (
    CASE "RVPOLAPSTATF"."HANDLETYPE" WHEN N'BTCH' THEN (
      CASE WHEN "RVPOLAPSTATF"."EVENTID" = N'000009000' THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'MDX' THEN (
      CASE WHEN "RVPOLAPSTATF"."EVENTID" = N'000009000' THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'EXTN' THEN (
      CASE WHEN (
        "RVPOLAPSTATF"."EVENTID" = N'000009001' OR "RVPOLAPSTATF"."EVENTID" = N'000009010' OR "RVPOLAPSTATF"."EVENTID" = N'000009011'
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'OLAP' THEN (
      CASE WHEN (
        "RVPOLAPSTATF"."EVENTID" = N'000009000' OR "RVPOLAPSTATF"."EVENTID" = N'000009010' OR "RVPOLAPSTATF"."EVENTID" = N'000009011'
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) ELSE CAST(
      0 AS DECIMAL(000021,000000)
    )
    END
  ) AS "TIMEDM",
  (
    CASE "RVPOLAPSTATF"."HANDLETYPE" WHEN N'PLAN' THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
      0 AS DECIMAL(000021,000000)
    )
    END
  ) AS "TIMEPLAN",
  (
    CASE "RVPOLAPSTATF"."HANDLETYPE" WHEN N'DFLT' THEN (
      CASE WHEN NOT (
        "RVPOLAPSTATF"."EVENTID" = N'000000001'
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) WHEN N'EXTN' THEN (
      CASE WHEN (
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000004500'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000009001'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000009010'
        ) AND
        NOT (
          "RVPOLAPSTATF"."EVENTID" = N'000009011'
        )
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    ) ELSE (
      CASE WHEN (
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'W3_T'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'W3_I'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'APPL'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'ITEM'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'DP'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'DIAL'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'BRFC'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'BTCH'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'MDX'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'PLAN'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'OLAP'
        ) AND
        NOT (
          "RVPOLAPSTATF"."HANDLETYPE" = N'F4'
        )
      ) THEN "RVPOLAPSTATF"."EVENTTIME" ELSE CAST(
        0 AS DECIMAL(000021,000000)
      )
      END
    )
    END
  ) AS "TIMENA"
FROM "CTE_RVPOLAPSTATF" AS "RVPOLAPSTATF"
)
,
CTE_RVPOLAPCQ AS
(
SELECT
  "RVPOLAPSTATM"."SESSIONUID",
  "RSDDSTAT_OLAP"."STEPUID",
  "RSDDSTAT_OLAP"."OBJNAME",
  (
    CAST(
      1 AS INTEGER
    )
  ) AS "OBJCOUNT"
FROM "CTE_RVPOLAPSTATM" AS "RVPOLAPSTATM" INNER JOIN "RSDDSTAT_OLAP" AS "RSDDSTAT_OLAP" ON (
  "RVPOLAPSTATM"."SESSIONUID" = "RSDDSTAT_OLAP"."SESSIONUID" AND
  "RVPOLAPSTATM"."OBJNAME" = "RSDDSTAT_OLAP"."OBJNAME" AND
  "RVPOLAPSTATM"."HANDLEID" = "RSDDSTAT_OLAP"."HANDLEID" AND
  "RSDDSTAT_OLAP"."HANDLETP" = N'OLAP' AND
  "RSDDSTAT_OLAP"."EVENTID" = N'000003010'
)
WHERE (
  "RVPOLAPSTATM"."EVENTID" = N'000003100' AND
  "RVPOLAPSTATM"."HANDLETYPE" = N'OLAP'
)
GROUP BY
  "RVPOLAPSTATM"."SESSIONUID",
  "RSDDSTAT_OLAP"."STEPUID",
  "RSDDSTAT_OLAP"."OBJNAME",
  "RSDDSTAT_OLAP"."HANDLEID"
)
,
CTE_RVPOLAPCF4 AS
(
SELECT
  "RVPOLAPSTATM"."SESSIONUID",
  "RVPOLAPSTATM"."STEPUID",
  "RVPOLAPSTATM"."OBJNAME",
  (
    CAST(
      1 AS INTEGER
    )
  ) AS "OBJCOUNT"
FROM "CTE_RVPOLAPSTATM" AS "RVPOLAPSTATM"
WHERE (
  "RVPOLAPSTATM"."EVENTID" = N'000006000' AND
  "RVPOLAPSTATM"."HANDLETYPE" = N'F4'
)
GROUP BY
  "RVPOLAPSTATM"."SESSIONUID",
  "RVPOLAPSTATM"."OBJNAME",
  "RVPOLAPSTATM"."HANDLEID",
  "RVPOLAPSTATM"."STEPUID"
)
,
CTE_RVPOLAPCOUNT AS
(
SELECT
  "RVPOLAPCQ"."SESSIONUID",
  "RVPOLAPCQ"."STEPUID",
  "RVPOLAPCQ"."OBJNAME",
  "RVPOLAPCQ"."OBJCOUNT"
FROM "CTE_RVPOLAPCQ" "RVPOLAPCQ"
UNION SELECT
  "RVPOLAPCF4"."SESSIONUID",
  "RVPOLAPCF4"."STEPUID",
  "RVPOLAPCF4"."OBJNAME",
  SUM(
    "RVPOLAPCF4"."OBJCOUNT"
  ) AS "OBJCOUNT"
FROM "CTE_RVPOLAPCF4" "RVPOLAPCF4"
GROUP BY
  "RVPOLAPCF4"."SESSIONUID",
  "RVPOLAPCF4"."STEPUID",
  "RVPOLAPCF4"."OBJNAME"
)
,
CTE_RVPOLAPSTATA1 AS
(
SELECT
  "RVPOLAPSTATM"."SESSIONUID",
  "RVPOLAPSTATM"."STEPUID",
  "RVPOLAPSTATM"."INFOPROV",
  "RVPOLAPSTATM"."OBJNAME",
  "RVPOLAPSTATM"."USERNAME",
  "RVPOLAPSTATM"."STARTTIME",
  "RVPOLAPSTATM"."TIME" AS "CALSECOND",
  (
    CONCAT(
      RTRIM (
        RTRIM(
          LEFT(
            RTRIM (
              "RVPOLAPSTATM"."TIME"
            ),
            4
          )
        )
      ),
      N'00'
    )
  ) AS "CALMINUTE",
  (
    CONCAT(
      RTRIM (
        RTRIM(
          LEFT(
            RTRIM (
              "RVPOLAPSTATM"."TIME"
            ),
            2
          )
        )
      ),
      N'0000'
    )
  ) AS "CALHOUR",
  "RVPOLAPSTATM"."CALDAY" AS "CALDAY",
  (
    RTRIM(
      LEFT(
        RTRIM (
          "RVPOLAPSTATM"."CALDAY"
        ),
        6
      )
    )
  ) AS "CALMONTH",
  (
    RTRIM(
      LEFT(
        RTRIM (
          "RVPOLAPSTATM"."CALDAY"
        ),
        4
      )
    )
  ) AS "CALYEAR",
  "=A0"."OBJCOUNT" AS "OBJCOUNT",
  SUM(
    "RVPOLAPSTATM"."TIMEFRONTEND"
  ) AS "TIMEFRONTEND",
  SUM(
    "RVPOLAPSTATM"."TIMEOLAP"
  ) AS "TIMEOLAP",
  SUM(
    "RVPOLAPSTATM"."TIMEDM"
  ) AS "TIMEDM",
  SUM(
    "RVPOLAPSTATM"."TIMEPLAN"
  ) AS "TIMEPLAN",
  SUM(
    "RVPOLAPSTATM"."TIMENA"
  ) AS "TIMENA"
FROM "CTE_RVPOLAPSTATM" "RVPOLAPSTATM" LEFT OUTER MANY TO ONE JOIN "CTE_RVPOLAPCOUNT" "=A0" ON (
  "=A0"."SESSIONUID" = "RVPOLAPSTATM"."SESSIONUID" AND
  "=A0"."STEPUID" = "RVPOLAPSTATM"."STEPUID" AND
  "=A0"."OBJNAME" = "RVPOLAPSTATM"."OBJNAME"
)
GROUP BY
  "RVPOLAPSTATM"."SESSIONUID",
  "RVPOLAPSTATM"."STEPUID",
  "RVPOLAPSTATM"."INFOPROV",
  "RVPOLAPSTATM"."OBJNAME",
  "RVPOLAPSTATM"."USERNAME",
  "RVPOLAPSTATM"."TIME",
  "RVPOLAPSTATM"."CALDAY",
  "RVPOLAPSTATM"."STARTTIME",
  "=A0"."OBJCOUNT"
)
,
CTE_RVIOLAPSTATA2 AS
(
SELECT
  "RVPOLAPSTATA1"."SESSIONUID",
  "RVPOLAPSTATA1"."STEPUID",
  "RVPOLAPSTATA1"."INFOPROV",
  "RVPOLAPSTATA1"."OBJNAME",
  "RVPOLAPSTATA1"."USERNAME",
  "RVPOLAPSTATA1"."STARTTIME",
  "RVPOLAPSTATA1"."CALSECOND",
  "RVPOLAPSTATA1"."CALMINUTE",
  "RVPOLAPSTATA1"."CALHOUR",
  "RVPOLAPSTATA1"."CALDAY",
  "RVPOLAPSTATA1"."CALMONTH",
  "RVPOLAPSTATA1"."CALYEAR",
  TSTMP_TO_TIMS(
    "RVPOLAPSTATA1"."STARTTIME",
    ABAP_USER_TIMEZONE(
      SESSION_CONTEXT(
        'APPLICATIONUSER'
      ),
      CURRENT_SCHEMA,
      SESSION_CONTEXT(
        'CDS_CLIENT'
      ),
      N'NULL'
    ),
    CURRENT_SCHEMA,
    SESSION_CONTEXT(
      'CDS_CLIENT'
    ),
    N'NULL'
  ) AS "USERTIME",
  TSTMP_TO_DATS(
    "RVPOLAPSTATA1"."STARTTIME",
    ABAP_USER_TIMEZONE(
      SESSION_CONTEXT(
        'APPLICATIONUSER'
      ),
      CURRENT_SCHEMA,
      SESSION_CONTEXT(
        'CDS_CLIENT'
      ),
      N'NULL'
    ),
    CURRENT_SCHEMA,
    SESSION_CONTEXT(
      'CDS_CLIENT'
    ),
    N'NULL'
  ) AS "USERDATE",
  TSTMP_TO_TIMS(
    "RVPOLAPSTATA1"."STARTTIME",
    ABAP_SYSTEM_TIMEZONE(
      CURRENT_SCHEMA,
      SESSION_CONTEXT(
        'CDS_CLIENT'
      ),
      N'NULL'
    ),
    CURRENT_SCHEMA,
    SESSION_CONTEXT(
      'CDS_CLIENT'
    ),
    N'NULL'
  ) AS "SYSTEMTIME",
  TSTMP_TO_DATS(
    "RVPOLAPSTATA1"."STARTTIME",
    ABAP_SYSTEM_TIMEZONE(
      CURRENT_SCHEMA,
      SESSION_CONTEXT(
        'CDS_CLIENT'
      ),
      N'NULL'
    ),
    CURRENT_SCHEMA,
    SESSION_CONTEXT(
      'CDS_CLIENT'
    ),
    N'NULL'
  ) AS "SYSTEMDATE",
  "RVPOLAPSTATA1"."OBJCOUNT",
  (
    CAST(
      CASE "RVPOLAPSTATA1"."TIMEFRONTEND" WHEN CAST(
        0 AS DECIMAL(000021,000000)
      ) THEN 0 ELSE 1
      END AS INTEGER
    )
  ) AS "OBJCOUNTFE",
  (
    CAST(
      CASE "RVPOLAPSTATA1"."TIMEOLAP" WHEN CAST(
        0 AS DECIMAL(000021,000000)
      ) THEN 0 ELSE 1
      END AS INTEGER
    )
  ) AS "OBJCOUNTOLAP",
  (
    CAST(
      CASE "RVPOLAPSTATA1"."TIMEDM" WHEN CAST(
        0 AS DECIMAL(000021,000000)
      ) THEN 0 ELSE 1
      END AS INTEGER
    )
  ) AS "OBJCOUNTDM",
  (
    CAST(
      CASE "RVPOLAPSTATA1"."TIMEPLAN" WHEN CAST(
        0 AS DECIMAL(000021,000000)
      ) THEN 0 ELSE 1
      END AS INTEGER
    )
  ) AS "OBJCOUNTPLAN",
  (
    CAST(
      CASE "RVPOLAPSTATA1"."TIMENA" WHEN CAST(
        0 AS DECIMAL(000021,000000)
      ) THEN 0 ELSE 1
      END AS INTEGER
    )
  ) AS "OBJCOUNTNA",
  "RVPOLAPSTATA1"."TIMEFRONTEND" AS "TIMEFRONTEND",
  "RVPOLAPSTATA1"."TIMEOLAP" AS "TIMEOLAP",
  "RVPOLAPSTATA1"."TIMEDM" AS "TIMEDM",
  "RVPOLAPSTATA1"."TIMEPLAN" AS "TIMEPLAN",
  "RVPOLAPSTATA1"."TIMENA" AS "TIMENA"
FROM "CTE_RVPOLAPSTATA1" AS "RVPOLAPSTATA1"
)
, cte_dist_data as
(
SELECT "CTE_RVIOLAPSTATA2"."INFOPROV" AS STAT_INFOPROV,
CASE SUBSTRING("CTE_RVIOLAPSTATA2"."INFOPROV",1,2)
WHEN '2C' THEN REPLACE("CTE_RVIOLAPSTATA2"."INFOPROV",'2C','') ELSE "CTE_RVIOLAPSTATA2"."INFOPROV" END AS "INFOPROV",
  "CTE_RVIOLAPSTATA2"."OBJNAME", MAX(CALYEAR) AS CALYEAR, MAX("TIMEOLAP") AS "TIMEOLAP", MAX("TIMEDM") AS "TIMEDM"
FROM CTE_RVIOLAPSTATA2 WHERE INFOPROV <> ''
GROUP BY
"CTE_RVIOLAPSTATA2"."INFOPROV",
  "CTE_RVIOLAPSTATA2"."OBJNAME"

)
SELECT D.DDLNAME, Q.*
FROM CTE_DIST_DATA AS Q
LEFT OUTER JOIN DDLDEPENDENCY AS D ON D.OBJECTNAME = Q.INFOPROV
ORDER BY 5 DESC
