/*
In order to be able to select in AMDP, one needs to create a view in _SYS_BIC
based on the CALCULATION_SCENARIOs that BPC 11 builds automatically

DROP VIEW "_SYS_BIC"."system-local.bw.bw2hana.cpmb/ZBPC<BPC_MODEL>_<VIEW_TYPE>";

CREATE COLUMN VIEW "_SYS_BIC"."system-local.bw.bw2hana.cpmb/ZBPC<BPC_MODEL>_<VIEW_TYPE>" WITH PARAMETERS (indexType=11,
'PARENTCALCINDEXSCHEMA'='SAPHANADB','PARENTCALCINDEX'='<BPC_CALC_SCENARIO>','PARENTCALCNODE'='/CPMB/ZOIGDZO$ADSO')

*/

The SQL is generated with the last SELECT at the bottom with
the WHERE CLAUSE
WHERE ADSO.APPLICATION_ID = <BPC_MODEL> AND ADSO.VIEW_TYPE NOT IN ('EXTR','CPMB') AND
( UJ.DIMENSION_TYPE IS NULL OR UJ.DIMENSION_TYPE = 'KEY' OR UJ.DIMENSION_TYPE = '__' ) AND
NOT ADSO.COLUMN_NAME IN
('0REQTSN_KEY','0REQTSN__0ASOURCE_KEY','0REQTSN__0AUSER_KEY','0DATAPAKID_KEY','0RECORD_KEY','0RECORDMODE_KEY','1TECHPROV_KEY','_IS_DELTA_KEY','_IS_FULL_KEY')

------------------------------- based on BPC metadat build the PROJECTION, FROM and GROUP BY CLAUSEs --------
with cte_bpc_attributes as
(
SELECT DISTINCT
"A"."APPSET_ID", 
'__' AS "DIMENSION_TYPE",
"D"."DIMENSION" AS "MAIN_DIMENSION",
REPLACE("D"."TECH_NAME",'/','$') AS "MAIN_DIMENSION_TECH",

"A"."DIMENSION",
"A"."TECH_NAME" AS "TECH_NAME",
REPLACE("A"."TECH_NAME",'/','$') AS "TECH_NAME2",
CASE WHEN "RW"."SOURCEHINT" IS NULL THEN ( CASE "A"."ATTRIBUTE_NAME" WHEN N'REVERSE' THEN N'REVERSE_' ELSE "A"."ATTRIBUTE_NAME" END) 
ELSE ( CONCAT( RTRIM ( "A"."ATTRIBUTE_NAME" ),N'1')) 
END AS "DIMENSION_NAME",
"A"."CAPTION" 
FROM ( 
  "UJA_DIM_ATTR" "A" INNER JOIN "UJA_DIMENSION" "D" ON ( 
    "A"."APPSET_ID" = "D"."APPSET_ID" AND 
    "A"."DIMENSION" = "D"."DIMENSION" AND 
    "A"."MANDT" = "D"."MANDT" AND 
    "D"."MANDT" = SESSION_CONTEXT( 'CDS_CLIENT' ) AND "A"."MANDT" = "D"."MANDT" 
  ) 
) LEFT OUTER JOIN "TRESE" "RW" ON 
  "RW"."NAME" = "A"."ATTRIBUTE_NAME"
WHERE "A"."APPSET_ID" = 'TRACTEBEL_TEMIS'
UNION
SELECT
"D"."APPSET_ID",
'KEY' AS "DIMENSION_TYPE",
"D"."DIMENSION" AS "MAIN_DIMENSION",
REPLACE("D"."TECH_NAME",'/','$') AS "MAIN_DIMENSION_TECH",
"D"."DIMENSION",
"D"."TECH_NAME", 
REPLACE("D"."TECH_NAME",'/','$') AS "TECH_NAME2",

"D"."DIMENSION" AS "DIMENSION_NAME",
"T"."DESCRIPTION" AS "CAPTION"
FROM "UJA_DIMENSION" AS "D"
INNER JOIN "UJA_DIMENSIONT" AS "T"
ON "T"."APPSET_ID" = "D"."APPSET_ID" AND "T"."DIMENSION" = "D"."DIMENSION" AND "T"."LANGU" = 'E'
WHERE "D"."APPSET_ID" = 'TRACTEBEL_TEMIS'
ORDER BY DIMENSION, DIMENSION_TYPE
)
,
cte_select_fields AS
(
SELECT
"APPSET_ID",
CASE "DIMENSION_TYPE"
WHEN '__'  THEN "MAIN_DIMENSION_TECH"||"DIMENSION_TYPE"||"TECH_NAME2"||'_KEY'
WHEN 'KEY' THEN "MAIN_DIMENSION_TECH"||'_'||"DIMENSION_TYPE"
END AS "COLUMN_NAME",
"DIMENSION_TYPE",
"MAIN_DIMENSION",
"MAIN_DIMENSION_TECH",
CASE WHEN "DIMENSION_TYPE" = '__' THEN "DIMENSION"||"DIMENSION_TYPE"||"DIMENSION_NAME" ELSE "DIMENSION" END AS "DIMENSION",
"TECH_NAME",
"TECH_NAME2",
"DIMENSION_NAME", 
"CAPTION"
FROM cte_bpc_attributes
)
,
cte_model_prefix as
(
SELECT APPLICATION_ID, APPL_PREFIX, INFOCUBE AS ADSO
FROM UJA_APPL
WHERE APPSET_ID = 'TRACTEBEL_TEMIS' AND NOT APPLICATION_ID IN ('SUCCESS_RATE','ATP','AGEING_BAL','MENU')
)
,
cte_adso_all as
(
SELECT "V"."SCHEMA_NAME", "V"."VIEW_NAME", 
CASE WHEN SUBSTRING("V"."VIEW_NAME",22,4) = '/CPM' THEN 'CPMB' WHEN SUBSTRING("V"."VIEW_NAME",22,4) = 'EXTR' THEN 'EXTR' WHEN SUBSTRING("V"."VIEW_NAME",22,4) = 'QO./' THEN 'QO'   END AS VIEW_TYPE, 
SUBSTR_BEFORE(SUBSTR_AFTER("V"."VIEW_NAME",'.'),'$ADSO') AS ADSO,
"V"."SCHEMA_NAME"||':'||SUBSTR_REGEXPR('(.+)\.(.+)' IN VIEW_NAME GROUP 1 ) AS SCENARIO_NAME
FROM "PUBLIC"."VIEWS" AS "V"
WHERE "V"."VIEW_NAME" LIKE '0BW:BIA:CPMB_Z%ADSO' AND "V"."IS_VALID" = 'TRUE' AND RIGHT("V"."VIEW_NAME",4) = 'ADSO'  
)
,
cte_scenarios AS
(
SELECT "V".*,
"SC"."IS_PERSISTENT","SC"."MEMORY_SIZE","CREATE_TIME", "COMPONENT"
FROM cte_adso_all AS "V"
INNER JOIN M_CE_CALCSCENARIOS AS SC
ON "V"."SCENARIO_NAME" = "SC"."SCENARIO_NAME"
)
,
cte_adso_views as
(
SELECT A.*, P.APPLICATION_ID, P.APPL_PREFIX 
FROM cte_scenarios as A
INNER JOIN cte_model_prefix AS P
ON P.ADSO = A.ADSO 
ORDER BY P.APPLICATION_ID
)
,
cte_adso_columns as
(
SELECT A.VIEW_TYPE, 
A.ADSO,A.APPLICATION_ID,A.APPL_PREFIX, REPLACE(REPLACE(C.COLUMN_NAME,'$CPMB$','/B28/S_'),'$B28$','/B28/') AS ADSO_COLUMN, C.*
FROM "PUBLIC"."VIEW_COLUMNS" AS C
INNER JOIN cte_adso_views AS A
ON C.SCHEMA_NAME = A.SCHEMA_NAME AND C.VIEW_NAME = A.VIEW_NAME
WHERE RIGHT(C.COLUMN_NAME,4) <> '_SID'
AND C.COLUMN_NAME <> '__numoffacttablerows'
ORDER BY C.VIEW_NAME, C.POSITION
)
SELECT
ADSO.VIEW_TYPE
,ADSO.ADSO
,UJ.APPSET_ID
,UJ.DIMENSION_TYPE
,ADSO.APPLICATION_ID
,ADSO.APPL_PREFIX
,ADSO.SCHEMA_NAME
,ADSO.VIEW_NAME
,ADSO.COLUMN_NAME
,CASE ADSO.COLUMN_NAME WHEN '0REQTSN_KEY' THEN 0 WHEN '$B28$S_SDATA' THEN 999 ELSE ADSO.POSITION END AS POSITION
,ADSO.DATA_TYPE_NAME
,ADSO.LENGTH
,ADSO.SCALE
,UJ.DIMENSION
,UJ.CAPTION,
CASE ADSO.COLUMN_NAME 
WHEN '0REQTSN_KEY' THEN '"'||ADSO.APPLICATION_ID||'"."'||ADSO.COLUMN_NAME||'" AS '||REPLACE(SUBSTRING(ADSO.COLUMN_NAME,2,10),'_KEY','')
WHEN '$B28$S_SDATA' THEN ',SUM("'||ADSO.APPLICATION_ID||'"."'||ADSO.COLUMN_NAME||'") AS SIGNEDDATA' 
ELSE CASE WHEN ADSO.POSITION = 1 THEN '"'||ADSO.APPLICATION_ID||'"."'||ADSO.COLUMN_NAME||'" AS '||UJ.DIMENSION
ELSE ',"'||ADSO.APPLICATION_ID||'"."'||ADSO.COLUMN_NAME||'" AS '||UJ.DIMENSION
END
END AS PROJECTION_COLUMN,
'FROM "'||ADSO.SCHEMA_NAME||'"."'||ADSO.VIEW_NAME||'" AS "'||ADSO.APPLICATION_ID||'"' AS FROM_CLAUSE,
CASE ADSO.COLUMN_NAME 
WHEN '0REQTSN_KEY' THEN
'"'||ADSO.APPLICATION_ID||'"."'||ADSO.COLUMN_NAME||'"' 
WHEN '$B28$S_SDATA' THEN ''
ELSE CASE WHEN ADSO.POSITION = 1 THEN '"'||ADSO.APPLICATION_ID||'"."'||ADSO.COLUMN_NAME||'"' 
ELSE ',"'||ADSO.APPLICATION_ID||'"."'||ADSO.COLUMN_NAME||'"'
END
END AS GROUP_BY_CLAUSE
FROM cte_adso_columns AS ADSO
LEFT OUTER JOIN cte_select_fields as UJ
ON ADSO.COLUMN_NAME = UJ.COLUMN_NAME
WHERE ADSO.APPLICATION_ID = 'Rates' AND ADSO.VIEW_TYPE NOT IN ('QO','CPMB') AND
/*QO UJ.DIMENSION_TYPE = 'KEY' AND */
NOT ADSO.COLUMN_NAME IN
('0REQTSN_KEY','0DATAPAKID_KEY','0RECORD_KEY','0RECORDMODE_KEY','1TECHPROV_KEY','_IS_DELTA_KEY','_IS_FULL_KEY')

ORDER BY VIEW_NAME, POSITION

key example:

SELECT
"SGA"."$CPMB$ZOD3GBJ_KEY" AS N_ACCOUNT
,"SGA"."$CPMB$ZOD3XXP_KEY" AS PARTNER
,"SGA"."$CPMB$ZOD5XXD_KEY" AS FIGURES
,"SGA"."$CPMB$ZOD5Y2R_KEY" AS PRODUCT
,"SGA"."$CPMB$ZODD2JW_KEY" AS SMART
,"SGA"."$CPMB$ZODI75I_KEY" AS TIME
,"SGA"."$CPMB$ZODP4UT_KEY" AS FUNCTIONAL_AREA
,"SGA"."$CPMB$ZODPS1W_KEY" AS EST_TYPE
,"SGA"."$CPMB$ZODTZZF_KEY" AS OBS
,"SGA"."$CPMB$ZODU8PO_KEY" AS WBS
,"SGA"."$CPMB$ZODVVCC_KEY" AS DATASRC
,"SGA"."$CPMB$ZODXJ55_KEY" AS OVH_LINE
,"SGA"."$CPMB$ZODYMR6_KEY" AS VERSION
,"SGA"."$CPMB$ZODYNME_KEY" AS CURRENCY

,SUM("SGA"."$B28$S_SDATA") AS SIGNEDDATA
FROM "SAPHANADB"."0BW:BIA:CPMB_ZOIJ4XC:QO./CPMB/ZOIJ4XC$ADSO" AS SGA
WHERE "SGA"."$CPMB$ZODI75I_KEY" = '2022_12'
GROUP BY
"SGA"."$CPMB$ZOD3GBJ_KEY"
,"SGA"."$CPMB$ZOD3XXP_KEY"
,"SGA"."$CPMB$ZOD5XXD_KEY"
,"SGA"."$CPMB$ZOD5Y2R_KEY"
,"SGA"."$CPMB$ZODD2JW_KEY"
,"SGA"."$CPMB$ZODI75I_KEY"
,"SGA"."$CPMB$ZODP4UT_KEY"
,"SGA"."$CPMB$ZODPS1W_KEY"
,"SGA"."$CPMB$ZODTZZF_KEY"
,"SGA"."$CPMB$ZODU8PO_KEY"
,"SGA"."$CPMB$ZODVVCC_KEY"
,"SGA"."$CPMB$ZODXJ55_KEY"
,"SGA"."$CPMB$ZODYMR6_KEY"
,"SGA"."$CPMB$ZODYNME_KEY"
LIMIT 10



full example:

SELECT
"SGA"."0REQTSN_KEY" AS REQTSN
,"SGA"."$CPMB$ZOD3GBJ_KEY" AS N_ACCOUNT
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ACCTYPE_KEY" AS N_ACCOUNT__ACCTYPE
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$CALC_KEY" AS N_ACCOUNT__CALC
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$RATETYP_KEY" AS N_ACCOUNT__RATETYPE
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP04G7_KEY" AS N_ACCOUNT__R_LEVEL
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP5F0K_KEY" AS N_ACCOUNT__INPUT_EXP_AGGR
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP5OZI_KEY" AS N_ACCOUNT__IS_EXP
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP8CEU_KEY" AS N_ACCOUNT__IS_AGGR
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPBF1S_KEY" AS N_ACCOUNT__IS_INVEST
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPCFZF_KEY" AS N_ACCOUNT__INPUT_DC
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPKXOQ_KEY" AS N_ACCOUNT__INTFEES_LOOP
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPM00O_KEY" AS N_ACCOUNT__INPUT_EXP
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPRK2B_KEY" AS N_ACCOUNT__IS_SGA999
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPU50R_KEY" AS N_ACCOUNT__NAT_AGGR
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPWD67_KEY" AS N_ACCOUNT__INTFEES_DEST
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPWOTG_KEY" AS N_ACCOUNT__SHORT_DESC
,"SGA"."$CPMB$ZOD3XXP_KEY" AS PARTNER
,"SGA"."$CPMB$ZOD3XXP__$CPMB$CALC_KEY" AS PARTNER__CALC
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ENTITY_KEY" AS PARTNER__ENTITY
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOP185K_KEY" AS PARTNER__BUS_AREA
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPFDOY_KEY" AS PARTNER__BAS_EQ_BA
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPJOMW_KEY" AS PARTNER__IS_BA
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPPH6Q_KEY" AS PARTNER__TP_INPUT
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPW7VY_KEY" AS PARTNER__TP9999CALC
,"SGA"."$CPMB$ZOD5XXD_KEY" AS FIGURES
,"SGA"."$CPMB$ZOD5XXD__$CPMB$CALC_KEY" AS FIGURES__CALC
,"SGA"."$CPMB$ZOD5Y2R_KEY" AS PRODUCT
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$CALC_KEY" AS PRODUCT__CALC
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP06WY_KEY" AS PRODUCT__IS_CORP
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP39JO_KEY" AS PRODUCT__GROWTH_DRIVERS
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP4PN4_KEY" AS PRODUCT__BUS_SEGM
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP5MWM_KEY" AS PRODUCT__BUS_LINE
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP8SJW_KEY" AS PRODUCT__STATUS
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP94HV_KEY" AS PRODUCT__SEGMENT
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP9S1G_KEY" AS PRODUCT__DESCRIPTION
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPD16I_KEY" AS PRODUCT__RESP_USER
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPDP9P_KEY" AS PRODUCT__NODE
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPFSYU_KEY" AS PRODUCT__SHORT_DESC
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPOY2S_KEY" AS PRODUCT__IS_ALLOC_PROD
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPRDHO_KEY" AS PRODUCT__GENERIC
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPWEJI_KEY" AS PRODUCT__FILTER
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPYMZB_KEY" AS PRODUCT__RESP_PERS
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPZ60D_KEY" AS PRODUCT__BUSAREA
,"SGA"."$CPMB$ZODD2JW_KEY" AS SMART
,"SGA"."$CPMB$ZODD2JW__$CPMB$CALC_KEY" AS SMART__CALC
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOP1S4Q_KEY" AS SMART__SEQ
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPCEV4_KEY" AS SMART__IRNR2
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPFNOF_KEY" AS SMART__R_LEVEL
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPIJC8_KEY" AS SMART__EBITDA
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPSFBM_KEY" AS SMART__CATEGORY
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPU9W5_KEY" AS SMART__NOPAT
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPUTSJ_KEY" AS SMART__ACCTYPE
,"SGA"."$CPMB$ZODI75I_KEY" AS TIME
,"SGA"."$CPMB$ZODI75I__$CPMB$BASPERD_KEY" AS TIME__BASE_PERIOD
,"SGA"."$CPMB$ZODI75I__$CPMB$CALC_KEY" AS TIME__CALC
,"SGA"."$CPMB$ZODI75I__$CPMB$PERIOD_KEY" AS TIME__PERIOD
,"SGA"."$CPMB$ZODI75I__$CPMB$TILEVEL_KEY" AS TIME__LEVEL1
,"SGA"."$CPMB$ZODI75I__$CPMB$YEAR_KEY" AS TIME__YEAR1
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOP8Y6V_KEY" AS TIME__PERIOD_LONG
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPBY4C_KEY" AS TIME__PREV_MONT
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPK388_KEY" AS TIME__NEXT_MON
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPMG2O_KEY" AS TIME__TIMEID
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPZ54V_KEY" AS TIME__MONTHNUM
,"SGA"."$CPMB$ZODP4UT_KEY" AS FUNCTIONAL_AREA
,"SGA"."$CPMB$ZODP4UT__$CPMB$CALC_KEY" AS FUNCTIONAL_AREA__CALC
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOP1RWM_KEY" AS FUNCTIONAL_AREA__USED_BY_NONPROMISE
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOP48VM_KEY" AS FUNCTIONAL_AREA__I_H6
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOP573Z_KEY" AS FUNCTIONAL_AREA__R_LEVEL
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPBIPK_KEY" AS FUNCTIONAL_AREA__PA_IN93
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPF74T_KEY" AS FUNCTIONAL_AREA__FA_ENGIE
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPF90D_KEY" AS FUNCTIONAL_AREA__I_H5
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPJ98I_KEY" AS FUNCTIONAL_AREA__R_H9
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPMWJ2_KEY" AS FUNCTIONAL_AREA__FA_ALL
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPOXBZ_KEY" AS FUNCTIONAL_AREA__SHORT_TXT
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPP7WN_KEY" AS FUNCTIONAL_AREA__FA_SGA
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPQOVC_KEY" AS FUNCTIONAL_AREA__R_H6
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPSS58_KEY" AS FUNCTIONAL_AREA__R_H5
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPT6VW_KEY" AS FUNCTIONAL_AREA__R_H2
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPV5JN_KEY" AS FUNCTIONAL_AREA__TYPE_ALLOC_PROD
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPYWUB_KEY" AS FUNCTIONAL_AREA__PA_BE74
,"SGA"."$CPMB$ZODPS1W_KEY" AS EST_TYPE
,"SGA"."$CPMB$ZODPS1W__$CPMB$CALC_KEY" AS EST_TYPE__CALC
,"SGA"."$CPMB$ZODPS1W__$CPMB$ZOPOVU2_KEY" AS EST_TYPE__DISPLAY
,"SGA"."$CPMB$ZODTZZF_KEY" AS OBS
,"SGA"."$CPMB$ZODTZZF__$CPMB$CALC_KEY" AS OBS__CALC
,"SGA"."$CPMB$ZODTZZF__$CPMB$CTCURRLC_KEY" AS OBS__CTRL_CURRENCY_NOT_LC
,"SGA"."$CPMB$ZODTZZF__$CPMB$CTLEVEL_KEY" AS OBS__CONTROL_LEVEL
,"SGA"."$CPMB$ZODTZZF__$CPMB$CURR_KEY" AS OBS__CURRENCY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP4YTY_KEY" AS OBS__ALLOC_PROD_TYPE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP5F68_KEY" AS OBS__DL_COMEX
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP6MUK_KEY" AS OBS__AGGR_ACT
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP6OIB_KEY" AS OBS__DISPLAY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP79NH_KEY" AS OBS__B09_CY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP7KVV_KEY" AS OBS__ENTITY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP8794_KEY" AS OBS__FILTER
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP8YJS_KEY" AS OBS__ALLOC_RULE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP965T_KEY" AS OBS__PROFIT_CNTR
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP96N9_KEY" AS OBS__IS_ENTITY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP9DVI_KEY" AS OBS__FX_TYPE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP9SKV_KEY" AS OBS__IS_COMP
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP9VFT_KEY" AS OBS__COMP_NAME
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPBI4Z_KEY" AS OBS__A01_SELECT
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPBMHC_KEY" AS OBS__R_BENT
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPBSHI_KEY" AS OBS__REVIEWER
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPC7IJ_KEY" AS OBS__R_LEVEL
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPCDQD_KEY" AS OBS__IS_EQ_SERVICE_GRP
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPCJHW_KEY" AS OBS__INPUT_COMPCODE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPCO6G_KEY" AS OBS__IS_ACTIVE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEEKQ_KEY" AS OBS__OBS_AGR
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEION_KEY" AS OBS__IS_SAP_COMP
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEJGK_KEY" AS OBS__BUDGET_INPUT
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEU74_KEY" AS OBS__BUS_AREA
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEUY9_KEY" AS OBS__SCC_RESP
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPGDDR_KEY" AS OBS__OVH_LINE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPGI0V_KEY" AS OBS__DL_COMPANY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPGPCG_KEY" AS OBS__BUS_ENTITY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPHSNG_KEY" AS OBS__IS_BA
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPIE04_KEY" AS OBS__FUNCTIONAL_AREA
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPISC8_KEY" AS OBS__CURRENCY2
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPIUV7_KEY" AS OBS__B02_SEGM02
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPKMXH_KEY" AS OBS__B02_SEGM01
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPMDTI_KEY" AS OBS__SMART_ID
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPMEMX_KEY" AS OBS__IS_BA_GRP
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPN3F5_KEY" AS OBS__B03_SEGM01
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPNF0F_KEY" AS OBS__IS_BAS_EQ_NODE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPNMI9_KEY" AS OBS__GEOZONE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPNW6R_KEY" AS OBS__B03_SEGM02
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPODJQ_KEY" AS OBS__PER_RES
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPP4F4_KEY" AS OBS__R_ENT
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPR9YY_KEY" AS OBS__B01_SELECT
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPRNP5_KEY" AS OBS__OWNER
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPS93B_KEY" AS OBS__BUDGET_INPUT_CY
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPU25N_KEY" AS OBS__ENT_NAME
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPUX70_KEY" AS OBS__COMP_CODE
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPX59Y_KEY" AS OBS__BUDGET_SELECT
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPXNG5_KEY" AS OBS__COMP_WOM_BA
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPY59P_KEY" AS OBS__INTCO
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPY9QM_KEY" AS OBS__ATP_DM
,"SGA"."$CPMB$ZODU8PO_KEY" AS WBS
,"SGA"."$CPMB$ZODU8PO__$CPMB$CALC_KEY" AS WBS__CALC
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP1GBP_KEY" AS WBS__OVH_LINE
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP23TV_KEY" AS WBS__BUSCLASS2
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP32J7_KEY" AS WBS__FA_BL
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP3WM0_KEY" AS WBS__BUSCLASS1
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP6ZJJ_KEY" AS WBS__FUNCTIONAL_AREA
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP7FH7_KEY" AS WBS__R_LEVEL
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPEM4O_KEY" AS WBS__BUS_AREA
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPFIT3_KEY" AS WBS__GENERIC_GA
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPI83R_KEY" AS WBS__COMP_CODE
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPK7Q8_KEY" AS WBS__SHORT_DESC
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPN9CO_KEY" AS WBS__WBS_SYS_STATUS
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPO7N6_KEY" AS WBS__RESP_CC
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPPQ6W_KEY" AS WBS__ACC_ASSIGN
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPR9C5_KEY" AS WBS__GENERIC
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPTGQX_KEY" AS WBS__RESP_CC_NODE
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPWKI4_KEY" AS WBS__PER_RES
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPXOV5_KEY" AS WBS__PROFIT_CNTR
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPYN86_KEY" AS WBS__WBS_SYS_STATUS_TXT
,"SGA"."$CPMB$ZODVVCC_KEY" AS DATASRC
,"SGA"."$CPMB$ZODVVCC__$CPMB$CALC_KEY" AS DATASRC__CALC
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOP1BEZ_KEY" AS DATASRC__DATASRC_STAGE
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOP3VCJ_KEY" AS DATASRC__COPYOPENING
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPG2E0_KEY" AS DATASRC__IS_CONSOL
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPQD8W_KEY" AS DATASRC__DIMLIST
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPSVF0_KEY" AS DATASRC__IS_CONVERTED
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPW3VV_KEY" AS DATASRC__OPUNING_DATASRC
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPYIQH_KEY" AS DATASRC__DATASRC_TYPE
,"SGA"."$CPMB$ZODXJ55_KEY" AS OVH_LINE
,"SGA"."$CPMB$ZODXJ55__$CPMB$CALC_KEY" AS OVH_LINE__CALC
,"SGA"."$CPMB$ZODXJ55__$CPMB$ZOP991K_KEY" AS OVH_LINE__SHORT_TEXT
,"SGA"."$CPMB$ZODXJ55__$CPMB$ZOPEJU7_KEY" AS OVH_LINE__WBS_HQ
,"SGA"."$CPMB$ZODXJ55__$CPMB$ZOPNJ2D_KEY" AS OVH_LINE__STD
,"SGA"."$CPMB$ZODYMR6_KEY" AS VERSION
,"SGA"."$CPMB$ZODYMR6__$CPMB$CALC_KEY" AS VERSION__CALC
,"SGA"."$CPMB$ZODYMR6__$CPMB$YEAR_KEY" AS VERSION__YEAR1
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPHPFZ_KEY" AS VERSION__VER
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPMBS8_KEY" AS VERSION__YEAR2
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPO655_KEY" AS VERSION__PR_VERSION
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPYGFJ_KEY" AS VERSION__YEAR1
,"SGA"."$CPMB$ZODYNME_KEY" AS CURRENCY
,"SGA"."$CPMB$ZODYNME__$CPMB$CALC_KEY" AS CURRENCY__CALC
,"SGA"."$CPMB$ZODYNME__$CPMB$ENTITY_KEY" AS CURRENCY__ENTITY
,"SGA"."$CPMB$ZODYNME__$CPMB$REPORT_KEY" AS CURRENCY__REPORTING
,"SGA"."$CPMB$ZODYNME__$CPMB$ZOPVZEJ_KEY" AS CURRENCY__CURRENCY_TYPE
,SUM("SGA"."$B28$S_SDATA") AS SIGNEDDATA
FROM "SAPHANADB"."0BW:BIA:CPMB_ZOIJ4XC:QO./CPMB/ZOIJ4XC$ADSO" AS SGA
WHERE "SGA"."$CPMB$ZODI75I_KEY" = '2022_12'
GROUP BY
"SGA"."0REQTSN_KEY"
,"SGA"."$CPMB$ZOD3GBJ_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ACCTYPE_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$RATETYP_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP04G7_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP5F0K_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP5OZI_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOP8CEU_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPBF1S_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPCFZF_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPKXOQ_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPM00O_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPRK2B_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPU50R_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPWD67_KEY"
,"SGA"."$CPMB$ZOD3GBJ__$CPMB$ZOPWOTG_KEY"
,"SGA"."$CPMB$ZOD3XXP_KEY"
,"SGA"."$CPMB$ZOD3XXP__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ENTITY_KEY"
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOP185K_KEY"
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPFDOY_KEY"
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPJOMW_KEY"
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPPH6Q_KEY"
,"SGA"."$CPMB$ZOD3XXP__$CPMB$ZOPW7VY_KEY"
,"SGA"."$CPMB$ZOD5XXD_KEY"
,"SGA"."$CPMB$ZOD5XXD__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZOD5Y2R_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP06WY_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP39JO_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP4PN4_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP5MWM_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP8SJW_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP94HV_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOP9S1G_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPD16I_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPDP9P_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPFSYU_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPOY2S_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPRDHO_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPWEJI_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPYMZB_KEY"
,"SGA"."$CPMB$ZOD5Y2R__$CPMB$ZOPZ60D_KEY"
,"SGA"."$CPMB$ZODD2JW_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOP1S4Q_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPCEV4_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPFNOF_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPIJC8_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPSFBM_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPU9W5_KEY"
,"SGA"."$CPMB$ZODD2JW__$CPMB$ZOPUTSJ_KEY"
,"SGA"."$CPMB$ZODI75I_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$BASPERD_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$PERIOD_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$TILEVEL_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$YEAR_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOP8Y6V_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPBY4C_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPK388_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPMG2O_KEY"
,"SGA"."$CPMB$ZODI75I__$CPMB$ZOPZ54V_KEY"
,"SGA"."$CPMB$ZODP4UT_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOP1RWM_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOP48VM_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOP573Z_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPBIPK_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPF74T_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPF90D_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPJ98I_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPMWJ2_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPOXBZ_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPP7WN_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPQOVC_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPSS58_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPT6VW_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPV5JN_KEY"
,"SGA"."$CPMB$ZODP4UT__$CPMB$ZOPYWUB_KEY"
,"SGA"."$CPMB$ZODPS1W_KEY"
,"SGA"."$CPMB$ZODPS1W__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODPS1W__$CPMB$ZOPOVU2_KEY"
,"SGA"."$CPMB$ZODTZZF_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$CTCURRLC_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$CTLEVEL_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$CURR_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP4YTY_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP5F68_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP6MUK_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP6OIB_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP79NH_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP7KVV_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP8794_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP8YJS_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP965T_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP96N9_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP9DVI_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP9SKV_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOP9VFT_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPBI4Z_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPBMHC_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPBSHI_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPC7IJ_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPCDQD_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPCJHW_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPCO6G_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEEKQ_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEION_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEJGK_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEU74_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPEUY9_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPGDDR_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPGI0V_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPGPCG_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPHSNG_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPIE04_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPISC8_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPIUV7_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPKMXH_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPMDTI_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPMEMX_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPN3F5_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPNF0F_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPNMI9_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPNW6R_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPODJQ_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPP4F4_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPR9YY_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPRNP5_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPS93B_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPU25N_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPUX70_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPX59Y_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPXNG5_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPY59P_KEY"
,"SGA"."$CPMB$ZODTZZF__$CPMB$ZOPY9QM_KEY"
,"SGA"."$CPMB$ZODU8PO_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP1GBP_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP23TV_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP32J7_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP3WM0_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP6ZJJ_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOP7FH7_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPEM4O_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPFIT3_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPI83R_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPK7Q8_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPN9CO_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPO7N6_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPPQ6W_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPR9C5_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPTGQX_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPWKI4_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPXOV5_KEY"
,"SGA"."$CPMB$ZODU8PO__$CPMB$ZOPYN86_KEY"
,"SGA"."$CPMB$ZODVVCC_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOP1BEZ_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOP3VCJ_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPG2E0_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPQD8W_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPSVF0_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPW3VV_KEY"
,"SGA"."$CPMB$ZODVVCC__$CPMB$ZOPYIQH_KEY"
,"SGA"."$CPMB$ZODXJ55_KEY"
,"SGA"."$CPMB$ZODXJ55__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODXJ55__$CPMB$ZOP991K_KEY"
,"SGA"."$CPMB$ZODXJ55__$CPMB$ZOPEJU7_KEY"
,"SGA"."$CPMB$ZODXJ55__$CPMB$ZOPNJ2D_KEY"
,"SGA"."$CPMB$ZODYMR6_KEY"
,"SGA"."$CPMB$ZODYMR6__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODYMR6__$CPMB$YEAR_KEY"
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPHPFZ_KEY"
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPMBS8_KEY"
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPO655_KEY"
,"SGA"."$CPMB$ZODYMR6__$CPMB$ZOPYGFJ_KEY"
,"SGA"."$CPMB$ZODYNME_KEY"
,"SGA"."$CPMB$ZODYNME__$CPMB$CALC_KEY"
,"SGA"."$CPMB$ZODYNME__$CPMB$ENTITY_KEY"
,"SGA"."$CPMB$ZODYNME__$CPMB$REPORT_KEY"
,"SGA"."$CPMB$ZODYNME__$CPMB$ZOPVZEJ_KEY"
,"SGA"."0REQTSN__0ASOURCE_KEY"
,"SGA"."0REQTSN__0AUSER_KEY"
LIMIT 10
