SELECT DISTINCT
D.DTP,
REPLACE(SUBSTR(SRC,1,LOCATE(SRC,'         ')),'_','$') AS ODP,
SRC,
SRCTP,
SRCTLOGO,
TGT,
TGTTP,
TGTTLOGO,
UPDMODE,
DELTAONLYONCE,
TRANID,
STARTROUTINE,
ENDROUTINE,
EXPERT,
TRANPROG
FROM RSBKDTP AS D
INNER JOIN RSBKDTPT AS T ON
D.DTP = T.DTP AND
D.OBJVERS = T.OBJVERS AND
T.LANGU = 'E' AND T.OBJVERS = 'A'
INNER JOIN RSTRAN AS TRFR ON TRFR.SOURCENAME = D.SRC AND TRFR.OBJVERS = 'A'
WHERE D.OBJVERS = 'A'
/* AND SRC LIKE '%TAB%'  OR SRC LIKE '%TD4%' OR SRC LIKE '%CDS%'
WHERE D.OBJVERS = 'A' AND NOT SRC LIKE '%TAB%'  AND NOT SRC LIKE '%TD4%' AND NOT SRC LIKE '%CDS%'*/
ORDER BY 3
