CLASS zcl_bw_rsbkdtp DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

public section.
INTERFACES if_amdp_marker_hdb .

CLASS-METHODS: read_dtp FOR TABLE FUNCTION ZBW_TF_RSBKDTP.

PROTECTED SECTION.
PRIVATE SECTION.
ENDCLASS.



CLASS zcl_bw_rsbkdtp IMPLEMENTATION.
METHOD read_dtp  BY database function for hdb language sqlscript using RSBKDTP RSBKDTPT RSTRAN.
RETURN
SELECT
DISTINCT
SRC,
REPLACE(SUBSTR(SRC,1,LOCATE(SRC,'         ')),'_','$') AS ODP,
D.DTP,
SRCTP,
SRCTLOGO,
TGT,
TGTTP,
TGTTLOGO,
UPDMODE,
DELTAONLYONCE,
TRANID,
STARTROUTINE,
ENDROUTINE,
EXPERT,
TRANPROG
FROM RSBKDTP AS D
INNER JOIN RSBKDTPT AS T ON
D.DTP = T.DTP AND
D.OBJVERS = T.OBJVERS AND
T.LANGU = 'E' AND T.OBJVERS = 'A'
INNER JOIN RSTRAN AS TRFR ON TRFR.SOURCENAME = D.SRC AND TRFR.OBJVERS = 'A'
WHERE D.OBJVERS = 'A'
;

ENDMETHOD. "read_dtp

ENDCLASS. "zcl_bw_rsbkdtp
